# -*- coding: utf-8 -*-
"""电气设备/工控方向种子数据（29 家）。薪资均为公开渠道聚合口径，仅供参考。"""
from .helpers import S

COMPANIES = [
    # ---------- 发电设备 ----------
    S("dongfang", "东方电气", "equipment", "发电设备", "央企", "发电设备制造",
      alias="东方电机/东电", apply_url="https://campus.dongfang.com", official_site="http://www.dongfang.com.cn",
      batch=["秋招", "春招"], status="未开启", positions=["电气设计", "电机设计", "工艺", "试验"],
      cities=["成都", "德阳", "广州南沙"], deadline_note="预计2026年9-10月，集团平台统一招聘",
      salary_text="转月约 8-12k×13",
      salary_structure="基本工资+绩效+年终，五险二金，央企福利",
      desc="发电设备三巨头之一（水电/火电/核电/风电主机），德阳基地规模大",
      ee_notes="电机/电气设计核心对口；广州南沙有东方电气风电基地；央企稳定，硕士在设计岗更有优势",
      tags=["S级对口", "央国企"], pinned=True),
    S("shanghai-electric", "上海电气", "equipment", "发电设备", "国企", "能源装备/工业装备",
      apply_url="https://campus.shanghai-electric.com", official_site="https://www.shanghai-electric.com",
      batch=["秋招", "春招"], status="未开启", positions=["电气设计", "风电", "核电设备", "自动化"],
      cities=["上海"], deadline_note="预计2026年9月开启",
      salary_text="转月约 9-13k×13",
      salary_structure="基本工资+绩效+年终，五险二金",
      desc="能源装备+工业装备大型上市国企（风电/核电/电梯/机床）",
      ee_notes="风电/核电设备电气岗对口；上海国企平台大",
      tags=["S级对口", "央国企"]),
    S("harbin", "哈电集团", "equipment", "发电设备", "央企", "发电设备制造",
      apply_url="https://campus.harbin-electric.com", official_site="https://www.harbin-electric.com",
      batch=["秋招"], status="未开启", positions=["电气设计", "电机", "工艺"],
      cities=["哈尔滨"], deadline_note="预计2026年9-10月",
      salary_text="转月约 7-10k×13",
      salary_structure="基本工资+绩效+年终，五险二金",
      desc="发电设备老牌央企（哈电机/哈锅/哈汽）",
      ee_notes="电机电气专业对口，东北央企稳定性强；薪资低于南方同业但生活成本低",
      tags=["S级对口", "央国企"]),

    # ---------- 输配电设备 ----------
    S("tbea", "特变电工", "equipment", "输配电设备", "民企", "变压器/输变电成套",
      apply_url="https://campus.tbea.com", official_site="https://www.tbea.com",
      batch=["秋招", "春招", "社招"], status="未开启", positions=["电气设计", "变压器研发", "工艺", "海外工程"],
      cities=["昌吉", "沈阳", "衡阳", "天津", "新疆基地"], deadline_note="预计2026年8月底-9月开启（制造类常提前）",
      salary_text="转月约 9-13k×13，新疆基地补贴高",
      salary_structure="基本工资+绩效+年终，五险一金，上市公司",
      desc="变压器全球产能龙头，输变电成套+新能源多晶硅双主业",
      ee_notes="电气类大量招；衡阳/沈阳/昌吉变压器基地为研发制造主体；愿意去新疆的晋升快",
      tags=["S级对口", "本科友好"], pinned=True),
    S("cee", "中国电气装备集团", "equipment", "输配电设备", "央企", "输配电设备",
      alias="电气装备集团", apply_url="https://campus.cec.com.cn", official_site="https://www.cec.com.cn",
      batch=["秋招", "春招"], status="未开启", positions=["电气研发", "一次设备设计", "工艺"],
      cities=["北京", "西安", "平顶山", "济南"], deadline_note="2021年新组建央企（原国网系装备资产），预计9月统一校招",
      salary_text="转月约 8-12k×13",
      salary_structure="基本工资+绩效+年终，五险二金，央企",
      desc="许继/平高/山东电工的母公司，输配电装备国家队",
      ee_notes="电气一次设备研发对口；下属许继（继保）平高（开关）按子公司招聘",
      tags=["S级对口", "央国企"]),
    S("pinggao", "平高集团", "equipment", "输配电设备", "央企", "高压开关",
      apply_url="https://campus.cec.com.cn", official_site="https://www.pinggao.com",
      batch=["秋招", "春招"], status="未开启", positions=["电气设计", "开关研发", "试验"],
      cities=["平顶山"], deadline_note="预计2026年9-10月",
      salary_text="转月约 7-10k×13",
      salary_structure="基本工资+绩效+年终，五险二金",
      desc="高压开关设备龙头（电气装备集团旗下）",
      ee_notes="高压/超高压开关电气设计对口；河南平顶山，成本洼地",
      tags=["S级对口", "央国企"]),
    S("sieyuan", "思源电气", "equipment", "输配电设备", "民企", "输配电设备",
      apply_url="https://campus.sieyuan.com", official_site="https://www.sieyuan.com",
      batch=["秋招", "春招", "实习", "社招"], status="未开启", positions=["电气研发", "硬件", "海外工程", "试验"],
      cities=["上海", "如皋", "深圳"], deadline_note="预计2026年8月底-9月开启，海外岗占比高",
      salary_text="转月约 10-14k×14，海外派驻年包可达 30w+",
      salary_structure="基本工资+绩效+年终，五险一金+补充公积金，上市公司",
      desc="民营输配电设备龙头（GIS/变压器/无功补偿），出海强劲",
      ee_notes="电气对口民营优解之一；研发在上海，制造在江苏如皋；海外工程师岗位电气需求大且高薪",
      tags=["S级对口", "本科友好"], pinned=True),
    S("chint", "正泰电器", "equipment", "输配电设备", "民企", "低压电器/光伏",
      apply_url="https://campus.chint.com", official_site="https://www.chint.com",
      batch=["秋招", "春招", "实习"], status="未开启", positions=["电气研发", "硬件", "结构", "新能源"],
      cities=["温州", "杭州", "上海"], deadline_note="预计2026年9月开启",
      salary_text="转月约 8-12k×13",
      salary_structure="基本工资+绩效+年终，五险一金，上市公司",
      desc="低压电器全球龙头，旗下正泰新能源（户用光伏第一）",
      ee_notes="电器研发/新能源板块均对口电气；温州总部成本友好",
      tags=["S级对口"], pinned=True),
    S("delixi", "德力西电气", "equipment", "输配电设备", "合资", "低压电器",
      apply_url="https://campus.delixi-electric.com", official_site="https://www.delixi-electric.com",
      batch=["秋招"], status="未开启", positions=["电气研发", "产品", "质量"],
      cities=["温州", "上海"], deadline_note="预计2026年9月",
      salary_text="转月约 8-11k×13",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="低压电器头部（德力西与施耐德合资背景）",
      ee_notes="低压电器研发/产品岗对口；管理规范化，外企式流程",
      tags=["S级对口"]),
    S("liangxin", "良信股份", "equipment", "输配电设备", "民企", "低压电器",
      alias="良信电器", apply_url="https://campus.nader.cn", official_site="https://www.nader.cn",
      batch=["秋招"], status="未开启", positions=["电气研发", "硬件", "测试"],
      cities=["上海"], deadline_note="预计2026年9月",
      salary_text="转月约 9-12k×13",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="中高端低压电器（新能源/数据中心配电）上市民企",
      ee_notes="电气研发对口；新能源配电赛道成长性好",
      tags=["S级对口"]),
    S("hongfa", "宏发股份", "equipment", "输配电设备", "民企", "继电器",
      apply_url="https://campus.hongfa.com", official_site="https://www.hongfa.com",
      batch=["秋招"], status="未开启", positions=["电气研发", "工艺", "自动化设备"],
      cities=["厦门"], deadline_note="预计2026年9月",
      salary_text="转月约 7-10k×13",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="继电器全球龙头（新能源车高压直流继电器放量）",
      ee_notes="电气/自动化对口，厦门宜居；非继保继电器，产品研发偏器件",
      tags=["高度相关"]),

    # ---------- 二次设备/继保 ----------
    S("nari", "国电南瑞", "equipment", "二次设备/继保", "央企", "电网自动化/继保",
      alias="南瑞集团", apply_url="https://campus.naritech.cn", official_site="https://www.naritech.cn",
      batch=["秋招", "春招", "实习"], status="未开启", positions=["电气研发", "继保", "软件", "硬件"],
      cities=["南京", "北京", "深圳"], deadline_note="预计2026年9月开启「未来空间站」校招，节奏较早",
      salary_text="转月约 12-16k×(13-15)，南京性价比高",
      salary_structure="基本工资+绩效+年终，五险二金，央企控股上市",
      desc="电网调度自动化/继保设备龙头（国网系），南京电气就业标杆",
      ee_notes="电气+计算机复合最受欢迎；研发岗以硕士为主，本科可投测试/工程岗；稳定且技术积累好",
      tags=["S级对口", "央国企", "本科友好"], pinned=True),
    S("nrec", "南瑞继保", "equipment", "二次设备/继保", "央企", "继电保护",
      alias="NR Electric", apply_url="https://campus.nrec.com", official_site="https://www.nrec.com",
      batch=["秋招"], status="未开启", positions=["继保研发", "硬件", "软件", "工程"],
      cities=["南京"], deadline_note="预计2026年9月开启",
      salary_text="转月约 13-18k×14，行业内薪资标杆",
      salary_structure="基本工资+绩效+年终，五险一金+企业年金",
      desc="继电保护全球头部（沈国荣院士创立，国网系）",
      ee_notes="电气继保方向技术天花板级雇主；研发门槛高（硕士+成绩好），工程/制造岗本科可投",
      tags=["S级对口", "央国企"], pinned=True),
    S("sifang", "四方股份", "equipment", "二次设备/继保", "民企", "继保/自动化",
      alias="四方继保", apply_url="https://campus.sifang.com", official_site="https://www.sifang.com",
      batch=["秋招"], status="未开启", positions=["继保研发", "硬件", "软件"],
      cities=["北京"], deadline_note="预计2026年9月",
      salary_text="转月约 10-14k×13",
      salary_structure="基本工资+绩效+年终，五险一金，上市公司",
      desc="继保+电网自动化第二梯队民企龙头（北京）",
      ee_notes="继保研发对口，北京落户积分可用；与南瑞/南瑞继保形成继保三强",
      tags=["S级对口"]),
    S("xj", "许继集团", "equipment", "二次设备/继保", "央企", "继保/直流输电",
      apply_url="https://campus.xjgc.com", official_site="https://www.xjgc.com",
      batch=["秋招"], status="未开启", positions=["电气研发", "继保", "直流控制保护"],
      cities=["许昌", "北京"], deadline_note="预计2026年9-10月（电气装备集团平台）",
      salary_text="转月约 7-11k×13，许昌成本洼地",
      salary_structure="基本工资+绩效+年终，五险二金",
      desc="继保+直流输电换流阀核心供应商（电气装备集团旗下）",
      ee_notes="特高压直流控制保护技术独特；许昌性价比可，研发硕士优先",
      tags=["S级对口", "央国企"]),
    S("nanzi", "国电南自", "equipment", "二次设备/继保", "央企", "电力自动化",
      alias="华电集团南自", apply_url="https://campus.sac-china.com", official_site="https://www.sac-china.com",
      batch=["秋招"], status="未开启", positions=["电气研发", "自动化", "软件"],
      cities=["南京"], deadline_note="预计2026年9-10月",
      salary_text="转月约 9-12k×13",
      salary_structure="基本工资+绩效+年终，五险二金",
      desc="电力自动化老牌国企（华电工程系，南京）",
      ee_notes="电厂自动化/电气研发对口；南京同类雇主中性价比一般但稳定",
      tags=["高度相关", "央国企"]),

    # ---------- 工控/传动 ----------
    S("inovance", "汇川技术", "equipment", "工控/传动", "民企", "工控/电机驱动/新能源车电控",
      apply_url="https://campus.inovance.com", official_site="https://www.inovance.com",
      batch=["秋招", "春招", "实习", "社招"], status="未开启", positions=["电机控制算法", "硬件", "嵌入式", "测试", "FAE"],
      cities=["深圳", "苏州", "武汉"], deadline_note="预计2026年8月底-9月初开启（工控节奏早），考公考研前抢人",
      salary_text="转月约 12-16k×(13-15)，年总包 20-28w",
      salary_structure="基本工资+绩效+年终（2-6个月），五险一金，上市公司期权激励部分岗位",
      desc="工控变频器/伺服国产龙头，新能源车电控+电梯电气大户",
      ee_notes="电气/自动化民营薪资天花板之一；电机控制、电力电子方向最对口；苏州/深圳基地，本科硕士都招",
      tags=["S级对口", "本科友好"], pinned=True),
    S("megmeet", "麦格米特", "equipment", "工控/传动", "民企", "电力电子/电源",
      apply_url="https://campus.megmeet.com", official_site="https://www.megmeet.com",
      batch=["秋招", "春招", "实习"], status="未开启", positions=["硬件开发", "电气设计", "结构", "嵌入式"],
      cities=["深圳", "株洲", "长沙"], deadline_note="预计2026年9月开启",
      salary_text="转月约 10-14k×(13-14)",
      salary_structure="基本工资+绩效+年终，五险一金，上市公司",
      desc="电力电子平台型公司（焊机/医疗/服务器电源/车规电源）",
      ee_notes="硬件/电源研发对口电气电子；株洲基地成本友好",
      tags=["S级对口"]),
    S("xinje", "信捷电气", "equipment", "工控/传动", "民企", "PLC/伺服",
      apply_url="https://campus.xinje.com", official_site="https://www.xinje.com",
      batch=["秋招"], status="未开启", positions=["电气研发", "嵌入式", "应用工程师"],
      cities=["无锡"], deadline_note="预计2026年9月",
      salary_text="转月约 8-12k×13",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="国产PLC/伺服头部（无锡）",
      ee_notes="工控应用/嵌入式对口；无锡制造业集群安家友好",
      tags=["S级对口"]),
    S("invt", "英威腾", "equipment", "工控/传动", "民企", "变频器/数据中心",
      apply_url="https://campus.invt.com.cn", official_site="https://www.invt.com.cn",
      batch=["秋招"], status="未开启", positions=["电气研发", "硬件", "应用"],
      cities=["深圳"], deadline_note="预计2026年9月",
      salary_text="转月约 8-11k×13",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="变频器/UPS 老牌民企（深圳）",
      ee_notes="电气硬件对口；深圳，性价比中等",
      tags=["高度相关"]),
    S("baiyun", "白云电器", "equipment", "输配电设备", "民企", "高低压成套",
      apply_url="https://campus.baiyun-electric.com", official_site="https://www.baiyun-electric.com",
      batch=["秋招"], status="未开启", positions=["电气设计", "成套一次/二次", "项目管理"],
      cities=["广州"], deadline_note="预计2026年9月",
      salary_text="转月约 7-10k×13",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="华南高低压成套设备龙头（广州，南网供应商）",
      ee_notes="成套设备电气设计对口；广州本地就业友好，与南网业务关联多",
      tags=["S级对口", "广东有岗", "本科友好"]),

    # ---------- 电源设备 ----------
    S("kstar", "科士达", "equipment", "电源设备", "民企", "UPS/数据中心/储能",
      apply_url="https://campus.kstar.com", official_site="https://www.kstar.com",
      batch=["秋招"], status="未开启", positions=["电气研发", "硬件", "结构"],
      cities=["深圳"], deadline_note="预计2026年9月",
      salary_text="转月约 9-12k×13",
      salary_structure="基本工资+绩效+年终，五险一金，上市公司",
      desc="UPS/数据中心电源+储能（深圳南山）",
      ee_notes="电源/储能电气研发对口；数据中心扩张期需求稳",
      tags=["高度相关", "广东有岗"]),
    S("east-group", "易事特", "equipment", "电源设备", "民企", "UPS/储能/充电桩",
      alias="易事特集团", apply_url="https://campus.eastgroup.com", official_site="https://www.eastgroup.com",
      batch=["秋招"], status="未开启", positions=["电气研发", "硬件", "储能系统"],
      cities=["东莞"], deadline_note="预计2026年9月",
      salary_text="转月约 8-11k×13",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="UPS/储能/充电桩（东莞松山湖）",
      ee_notes="储能/充电设施电气对口；东莞成本友好",
      tags=["高度相关", "广东有岗"]),
    S("delta", "台达电子", "equipment", "电源设备", "外企", "电源管理",
      alias="中达电通", apply_url="https://campus.deltaelectronics.com", official_site="https://www.delta-emea.com",
      batch=["秋招", "实习"], status="未开启", positions=["硬件研发", "电源工程师", "测试"],
      cities=["上海", "东莞/吴江基地"], deadline_note="预计2026年9月",
      salary_text="转月约 9-12k×13",
      salary_structure="基本工资+绩效+年终，五险一金，台资规范管理",
      desc="全球电源管理龙头（服务器电源/车电/工业电源）",
      ee_notes="电源硬件研发对口；外企流程规范，加班相对可控",
      tags=["高度相关", "外企"]),

    # ---------- 外企电气 ----------
    S("siemens", "西门子（中国）", "equipment", "外企电气", "外企", "电气自动化/数字化",
      apply_url="https://jobs.siemens.com/careers?location=China", official_site="https://www.siemens.com.cn",
      batch=["秋招", "实习", "社招"], status="未开启", positions=["电气研发", "FAE", "数字化", "销售工程师"],
      cities=["北京", "上海", "广州", "成都"], deadline_note="管培/校招常年滚动，秋招高峰9-10月",
      salary_text="转月约 10-15k×13，福利完善",
      salary_structure="13薪+浮动奖金，五险一金全额，补充商业保险，工作生活平衡好",
      desc="电气自动化全球巨头（工控/输配电/数字化）",
      ee_notes="外企电气标杆；技术+销售管培都招电气；英语重要；WLB好适合长期发展",
      tags=["S级对口", "外企"], pinned=True),
    S("abb", "ABB（中国）", "equipment", "外企电气", "外企", "电气/机器人/自动化",
      apply_url="https://global.abb/group/en/careers", official_site="https://new.abb.com/cn",
      batch=["秋招", "实习", "社招"], status="未开启", positions=["电气研发", "电机/传动", "销售工程师"],
      cities=["北京", "上海", "厦门", "广州"], deadline_note="校招滚动进行，9-10月高峰",
      salary_text="转月约 10-15k×13",
      salary_structure="13薪+奖金，五险一金全额，外企福利",
      desc="电气与自动化百年巨头（厦门低压/上海总部）",
      ee_notes="电气研发/传动/低压电器对口；厦门基地待遇性价比高",
      tags=["S级对口", "外企"], pinned=True),
    S("schneider", "施耐德电气", "equipment", "外企电气", "外企", "配电/自动化/能源管理",
      apply_url="https://www.se.com/ww/en/about-us/careers/overview.jsp", official_site="https://www.se.com/cn",
      batch=["秋招", "实习", "社招"], status="未开启", positions=["硬件研发", "配电设计", "管培生"],
      cities=["北京", "上海", "广州", "深圳"], deadline_note="管培项目9月开放申请，滚动面试",
      salary_text="转月约 11-15k×13，外企福利标杆",
      salary_structure="13薪+奖金，五险一金全额+补充公积金，弹性工作",
      desc="能源管理+工业自动化全球龙头，外企电气口碑第一梯队",
      ee_notes="电气专业外企首选之一；管培项目竞争激烈，重英语和领导力经历",
      tags=["S级对口", "外企"], pinned=True),
    S("eaton", "伊顿（中国）", "equipment", "外企电气", "外企", "电气/航空航天",
      apply_url="https://www.eaton.com/cn/zh-cn/company/careers.html", official_site="https://www.eaton.com.cn",
      batch=["秋招", "实习"], status="未开启", positions=["电气研发", "配电产品", "销售工程师"],
      cities=["上海", "苏州", "广州", "深圳（山特电子，UPS/数据中心电源）"], deadline_note="预计2026年9月滚动；深圳山特为伊顿旗下 UPS 品牌",
      salary_text="转月约 10-14k×13",
      salary_structure="13薪+奖金，五险一金全额，外企福利",
      desc="美国电气/动力管理巨头（中低压配电/UPS）",
      ee_notes="配电产品研发与销售岗对口电气；华南有基地",
      tags=["S级对口", "外企"]),
    S("rockwell", "罗克韦尔自动化", "equipment", "外企电气", "外企", "工业自动化",
      alias="Rockwell Automation", apply_url="https://www.rockwellautomation.com/en-us/company/careers.html", official_site="https://www.rockwellautomation.com",
      batch=["秋招", "实习"], status="未开启", positions=["应用工程师", "PLC/自动化", "销售"],
      cities=["上海", "大连", "广州"], deadline_note="预计2026年9月滚动",
      salary_text="转月约 10-14k×13",
      salary_structure="13薪+奖金，五险一金全额，外企福利",
      desc="工业自动化（PLC 鼻祖级）美企",
      ee_notes="自动化/电气对口，FAE 岗锻炼全面；英语要求高",
      tags=["高度相关", "外企"]),
    S("hitachi-energy", "日立能源", "equipment", "外企电气", "外企", "电网设备/换流阀",
      alias="Hitachi Energy", apply_url="https://careers.hitachienergy.com", official_site="https://www.hitachienergy.com/cn",
      batch=["秋招"], status="未开启", positions=["电气研发", "换流阀", "变压器", "工程"],
      cities=["上海", "北京", "广州"], deadline_note="预计2026年9月",
      salary_text="转月约 11-15k×13",
      salary_structure="13薪+奖金，五险一金全额，外企福利",
      desc="原ABB电网业务，高压直流/变压器全球龙头",
      ee_notes="特高压直流/变压器技术岗位对口电气；上海/广州有基地",
      tags=["S级对口", "外企"]),
    S("ge-vernova", "GE Vernova（电气化）", "equipment", "外企电气", "外企", "电力设备/电网",
      apply_url="https://www.gevernova.com/careers", official_site="https://www.gevernova.com",
      batch=["秋招"], status="未开启", positions=["电气研发", "开关设备", "电网解决方案"],
      cities=["上海", "无锡"], deadline_note="预计2026年9-10月",
      salary_text="转月约 11-15k×13",
      salary_structure="13薪+奖金，五险一金全额，外企福利",
      desc="GE 拆分后的电力/电气化公司",
      ee_notes="电网设备/开关研发对口；岗位少但质量高",
      tags=["高度相关", "外企"]),
    S("jinpan", "金盘科技", "equipment", "输配电设备", "民企", "干式变压器/数据中心",
      apply_url="https://campus.jinpan.com", official_site="https://www.jinpan.com.cn",
      batch=["秋招"], status="未开启", positions=["电气研发", "变压器设计", "工艺", "海外工程"],
      cities=["海口", "武汉", "桂林", "美国基地"], deadline_note="预计2026年9月",
      salary_text="转月约 10-14k×13",
      salary_structure="基本工资+绩效+年终，五险一金，上市公司",
      desc="干式变压器龙头，AI 数据中心变压器出口爆单",
      ee_notes="数据中心扩容潮核心受益者，电气研发/工艺需求旺；海口基地性价比可",
      tags=["S级对口"]),
    S("mingyang-elec", "明阳电气", "equipment", "输配电设备", "民企", "变压器/成套设备",
      alias="明阳集团电气板块", apply_url="https://campus.mingyangdianqi.com", official_site="https://www.mingyangdianqi.com",
      batch=["秋招"], status="未开启", positions=["电气设计", "变压器/成套研发", "工艺"],
      cities=["中山"], deadline_note="预计2026年9月",
      salary_text="转月约 8-12k×13",
      salary_structure="基本工资+绩效+年终，五险一金，上市公司",
      desc="明阳集团旗下输配电设备上市企业（中山，风电箱变主力供应商）",
      ee_notes="与明阳智能（整机）区分：这家做变压器/成套；中山本地，新能源配套赛道",
      tags=["S级对口", "广东有岗", "本科友好"]),
    S("tgood", "特锐德", "equipment", "输配电设备", "民企", "箱式变电/充电网",
      alias="TGOOD", apply_url="https://campus.tec.cn", official_site="https://www.tec.cn",
      batch=["秋招"], status="未开启", positions=["电气研发", "箱变设计", "充电网", "电力电子"],
      cities=["青岛", "全国项目"], deadline_note="预计2026年9月",
      salary_text="转月约 8-12k×13",
      salary_structure="基本工资+绩效+年终，五险一金，创业板上市",
      desc="箱式变电龙头 + 特来电充电网（青岛）",
      ee_notes="充电基础设施赛道；电气设计/电力电子对口，出差看项目",
      tags=["S级对口"]),
    S("kewa", "科华数据", "equipment", "电源设备", "民企", "UPS/数据中心/储能",
      alias="KELONG", apply_url="https://campus.kehua.com", official_site="https://www.kehua.com",
      batch=["秋招"], status="未开启", positions=["电气研发", "电源硬件", "数据中心", "储能系统"],
      cities=["厦门", "深圳"], deadline_note="预计2026年9月",
      salary_text="转月约 9-13k×13",
      salary_structure="基本工资+绩效+年终，五险一金，上市公司",
      desc="UPS/数据中心电源+储能老牌厂商（厦门）",
      ee_notes="AI 算力带动数据中心电气需求爆发；电源研发电气对口",
      tags=["S级对口"]),
    S("sinexcel", "盛弘股份", "equipment", "电源设备", "民企", "充电桩/储能PCS",
      apply_url="https://campus.sinexcel.com", official_site="https://www.sinexcel.com",
      batch=["秋招"], status="未开启", positions=["电气研发", "电力电子硬件", "测试"],
      cities=["深圳"], deadline_note="预计2026年9月",
      salary_text="转月约 11-15k×(13-14)",
      salary_structure="基本工资+绩效+年终，五险一金，上市公司",
      desc="充电桩模块/储能 PCS/电能质量设备（深圳）",
      ee_notes="电力电子方向对口度极高；深圳，体量小于汇川但技术同类",
      tags=["S级对口", "广东有岗"]),
    S("estun", "埃斯顿自动化", "equipment", "工控/传动", "民企", "工业机器人/运动控制",
      alias="ESTUN", apply_url="https://campus.estun.com", official_site="https://www.estun.com",
      batch=["秋招"], status="未开启", positions=["电气工程师", "伺服研发", "应用工程师"],
      cities=["南京"], deadline_note="预计2026年9月",
      salary_text="转月约 9-13k×13",
      salary_structure="基本工资+绩效+年终，五险一金，上市公司",
      desc="国产工业机器人出货第一 + 伺服运动控制（南京）",
      ee_notes="机器人+工控双赛道；电气/自动化对口，调试与应用岗本科友好",
      tags=["高度相关"]),
    S("danfoss", "丹佛斯（中国）", "equipment", "外企电气", "外企", "变频传动/液压",
      alias="Danfoss", apply_url="https://www.danfoss.com/en/about-danfoss/careers/vacancies/", official_site="https://www.danfoss.cn",
      batch=["秋招", "实习"], status="未开启", positions=["电气研发", "变频器", "应用工程师"],
      cities=["天津", "浙江海盐"], deadline_note="预计2026年9月滚动",
      salary_text="转月约 10-14k×13",
      salary_structure="13薪+奖金，五险一金全额，外企福利，WLB好",
      desc="丹麦传动/变频器巨头（海盐建大型传动工厂）",
      ee_notes="电力电子/传动研发对口；外企节奏健康，适合长期主义",
      tags=["高度相关", "外企"]),
    S("legrand", "罗格朗（中国）", "equipment", "外企电气", "外企", "低压电器/线缆管理",
      alias="Legrand/TCL-罗格朗", apply_url="https://www.legrand.com.cn", official_site="https://www.legrand.com.cn",
      batch=["秋招"], status="未开启", positions=["电气研发", "产品工程师", "销售工程师"],
      cities=["上海", "惠州"], deadline_note="预计2026年9月",
      salary_text="转月约 9-12k×13",
      salary_structure="13薪+奖金，五险一金全额，法资外企福利",
      desc="全球低压电器/电工龙头（与 TCL 合资背景，惠州有基地）",
      ee_notes="低压电器研发对口；惠州岗位离家近的同学留意",
      tags=["高度相关", "外企", "广东有岗"]),
]
