# -*- coding: utf-8 -*-
"""泛工科延伸方向种子数据（35 家）。薪资均为公开渠道聚合口径，仅供参考。"""
from .helpers import S

COMPANIES = [
    # ---------- ICT硬件 ----------
    S("huawei", "华为", "general", "ICT硬件", "民企", "ICT/终端/智能汽车",
      apply_url="https://career.huawei.com", official_site="https://www.huawei.com",
      batch=["秋招", "春招", "实习", "社招"], status="进行中", positions=["硬件开发", "电气/电源", "结构", "嵌入式", "测试"],
      cities=["深圳", "东莞", "上海", "南京", "西安", "成都"], deadline_note="2027届秋招已于8月底上线启动（核验确认），各岗位滚动面试",
      salary_text="本科转月约 15-22k×(15-16)+TUP，年总包 25-40w",
      salary_structure="月薪×15/16+TUP虚拟受限股分红+项目奖金，五险一金高基数",
      desc="ICT全球龙头，硬件/电气需求覆盖电源、能源、车BU",
      ee_notes="电气生可投：数字能源、电源硬件、结构/热设计、制造工艺；平台薪酬行业顶级；强度大；英语&成绩要求高",
      tags=["高度相关", "本科友好"], pinned=True),
    S("zte", "中兴通讯", "general", "ICT硬件", "国企", "通信设备",
      apply_url="https://campus.zte.com.cn", official_site="https://www.zte.com.cn",
      batch=["秋招", "春招", "实习", "社招"], status="未开启", positions=["硬件开发", "电源", "嵌入式", "测试"],
      cities=["深圳", "南京", "上海", "西安", "成都"], deadline_note="预计2026年8月底-9月开启「蓝剑/青苗」计划",
      salary_text="本科转月约 12-16k×(14-15)",
      salary_structure="基本工资+绩效+年终，五险一金，国企背景市场化薪酬",
      desc="通信设备全球第四，电源/硬件岗位电气对口",
      ee_notes="电源研发/硬件测试对口电气；深圳/南京双主场；比华为门槛稍低",
      tags=["高度相关"]),
    S("xiaomi", "小米集团", "general", "ICT硬件", "民企", "手机/IoT/汽车",
      apply_url="https://hr.xiaomi.com/campus", official_site="https://www.xiaomi.com",
      batch=["秋招", "春招", "实习"], status="未开启", positions=["硬件研发", "电源工程师", "结构", "测试", "汽车电气"],
      cities=["北京", "上海", "深圳", "南京", "武汉"], deadline_note="预计2026年9月开启「未来星」校招",
      salary_text="本科转月约 13-18k×15（含签字费另计）",
      salary_structure="月薪×15为主，五险一金，部分岗位股票",
      desc="手机+IoT+汽车三线，北京/亦庄汽车工厂扩张",
      ee_notes="消费电子电源/硬件+小米汽车工厂电气岗都对电气开放；15薪体系诚意足",
      tags=["高度相关"]),
    S("oppo", "OPPO", "general", "ICT硬件", "民企", "手机/智能硬件",
      apply_url="https://campus.oppo.com", official_site="https://www.oppo.com",
      batch=["秋招", "春招", "实习"], status="未开启", positions=["硬件开发", "电源工程师", "测试", "结构"],
      cities=["深圳", "东莞", "成都", "印度/东南亚"], deadline_note="预计2026年8月底-9月开启",
      salary_text="本科转月约 12-16k×(14-15)",
      salary_structure="月薪×14/15，五险一金，绩效浮动",
      desc="手机全球前四（东莞长安总部）",
      ee_notes="快充/电源研发电气对口度高；东莞总部生活成本友好",
      tags=["高度相关", "广东有岗"]),
    S("vivo", "vivo", "general", "ICT硬件", "民企", "手机/智能硬件",
      apply_url="https://campus.vivo.com", official_site="https://www.vivo.com",
      batch=["秋招", "春招", "实习"], status="未开启", positions=["硬件开发", "电源", "结构", "测试"],
      cities=["东莞", "深圳", "南京", "重庆"], deadline_note="预计2026年8月底-9月开启",
      salary_text="本科转月约 12-16k×(14-15)",
      salary_structure="月薪×14/15，五险一金",
      desc="手机全球前三（东莞总部）",
      ee_notes="与OPPO类似，快充/电源研发对口；东莞长安镇总部",
      tags=["高度相关", "广东有岗"]),
    S("honor", "荣耀终端", "general", "ICT硬件", "民企", "手机/智能硬件",
      alias="HONOR", apply_url="https://career.honor.com", official_site="https://www.honor.com",
      batch=["秋招", "春招"], status="未开启", positions=["硬件研发", "电源工程师", "测试"],
      cities=["深圳", "上海", "西安"], deadline_note="预计2026年9月",
      salary_text="本科转月约 12-16k×(14-15)",
      salary_structure="月薪+年终，五险一金",
      desc="原华为终端体系独立（深圳）",
      ee_notes="华为系硬件打法；电源研发对口",
      tags=["高度相关", "广东有岗"]),
    S("dji", "大疆创新", "general", "ICT硬件", "民企", "无人机/影像/车载",
      alias="DJI", apply_url="https://we.dji.com/zh-CN/campus", official_site="https://www.dji.com",
      batch=["秋招", "春招", "实习"], status="未开启", positions=["电气工程师", "硬件", "电机驱动", "测试"],
      cities=["深圳", "东莞松山湖"], deadline_note="预计2026年8月底-9月初开启「拓疆者」，节奏早",
      salary_text="本科转月约 15-20k×(14-15)，年总包 25-35w",
      salary_structure="月薪+年终（3-5个月），五险一金全额",
      desc="全球无人机绝对龙头（深圳），产品定义能力强",
      ee_notes="电机驱动/电源/硬件电气对口，深圳硬件天花板级薪酬；笔试重专业基础；8月底抢开",
      tags=["高度相关", "广东有岗"], pinned=True),
    S("hikvision", "海康威视", "general", "ICT硬件", "国企", "安防/IoT",
      apply_url="https://campus.hikvision.com", official_site="https://www.hikvision.com",
      batch=["秋招", "春招", "实习"], status="未开启", positions=["硬件开发", "电源", "嵌入式", "测试"],
      cities=["杭州", "武汉", "成都", "西安"], deadline_note="预计2026年8月底-9月开启",
      salary_text="本科转月约 11-15k×(13-15)",
      salary_structure="基本工资+绩效+年终，五险一金+企业年金",
      desc="安防全球龙头（杭州），硬件岗位规模大",
      ee_notes="电源/硬件研发对口；杭州国企背景待遇体系成熟",
      tags=["高度相关", "央国企"]),
    S("luxshare", "立讯精密", "general", "ICT硬件", "民企", "消费电子制造",
      apply_url="https://campus.luxshare-ict.com", official_site="https://www.luxshare-ict.com",
      batch=["秋招", "社招"], status="未开启", positions=["设备工程师", "电气工程师", "工艺", "NPI"],
      cities=["东莞", "昆山", "江西", "越南"], deadline_note="预计2026年9月，制造体系常年招",
      salary_text="本科转月约 8-11k×(13-14)",
      salary_structure="基本工资+加班费+绩效，五险一金",
      desc="消费电子代工龙头（AirPods/连接器）",
      ee_notes="工厂电气/自动化设备岗需求大；制造强度大，适合积累产线经验",
      tags=["相关", "广东有岗", "本科友好"]),
    S("fii", "工业富联", "general", "ICT硬件", "民企", "电子制造/服务器",
      alias="富士康母体上市", apply_url="https://campus.foxconn.com", official_site="https://www.fii-foxconn.com",
      batch=["秋招", "社招"], status="未开启", positions=["设备工程师", "电气工程师", "厂务", "工艺"],
      cities=["深圳", "郑州", "昆山", "成都"], deadline_note="预计2026年9月，各园区滚动",
      salary_text="本科转月约 7-10k×(13-14)+加班费",
      salary_structure="基本工资+加班费+绩效，五险一金",
      desc="全球最大电子代工体系，AI服务器新增长",
      ee_notes="厂务电气/设备岗量大门槛友好；AI服务器产线扩张带来新机会",
      tags=["相关", "本科友好"]),
    S("mindray", "迈瑞医疗", "general", "医疗器械", "民企", "医疗器械",
      apply_url="https://campus.mindray.com", official_site="https://www.mindray.com",
      batch=["秋招", "春招", "实习"], status="未开启", positions=["硬件研发", "电气工程师", "测试", "法规注册"],
      cities=["深圳", "南京", "武汉", "成都"], deadline_note="预计2026年9月开启",
      salary_text="本科转月约 12-15k×(14-15)",
      salary_structure="基本工资+绩效+年终，五险一金全额",
      desc="国产医疗器械龙头（深圳），监护仪全球前二",
      ee_notes="医疗设备硬件/电气研发对口，深圳，利润率高的赛道；研发以电子背景为主，电气可投测试/工艺",
      tags=["高度相关", "广东有岗"]),
    S("united-imaging", "联影医疗", "general", "医疗器械", "国企", "高端医疗影像",
      alias="United Imaging", apply_url="https://campus.united-imaging.com", official_site="https://www.united-imaging.com",
      batch=["秋招"], status="未开启", positions=["电气工程师", "系统硬件", "测试"],
      cities=["上海", "武汉", "常州"], deadline_note="预计2026年9月",
      salary_text="本科转月约 12-15k×(13-14)",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="CT/MRI 高端影像国产替代龙头（上海）",
      ee_notes="大型设备电气系统（供配电/安全）对口；国产高端制造标杆",
      tags=["高度相关"]),

    # ---------- 家电 ----------
    S("midea", "美的集团", "general", "家电", "民企", "家电/机器人/楼宇科技",
      apply_url="https://campus.midea.com", official_site="https://www.midea.com",
      batch=["秋招", "春招", "实习", "社招"], status="进行中", positions=["电气工程师", "硬件研发", "设备", "自动化"],
      cities=["佛山", "合肥", "芜湖", "武汉", "上海"], deadline_note="2027届校招8月已开启（「美苗」体系），滚动面试",
      salary_text="本科转月约 9-13k×(13-16)，年总包 14-22w",
      salary_structure="月薪+年终（1-4个月），五险一金+企业年金，免费食宿部分基地",
      desc="家电全球龙头+机器人（库卡）+楼宇科技，佛山顺德总部",
      ee_notes="广东就业大户；电气可投：产品硬件、工厂电气、自动化产线；管理培训生体系成熟；8月已开",
      tags=["S级对口", "广东有岗", "本科友好"], pinned=True),
    S("gree", "格力电器", "general", "家电", "国企", "家电/工业制品",
      apply_url="https://campus.gree.com", official_site="https://www.gree.com",
      batch=["秋招", "春招", "社招"], status="未开启", positions=["电气设计", "研发工程师", "设备", "质量"],
      cities=["珠海", "芜湖", "武汉", "合肥"], deadline_note="预计2026年9月开启",
      salary_text="本科转月约 8-11k×13",
      salary_structure="基本工资+绩效+年终，五险一金+珠海住房补贴政策",
      desc="空调龙头（珠海总部），制造业体系完整",
      ee_notes="电机/电气设计对口（压缩机/电机研发）；珠海安家有人才补贴",
      tags=["S级对口", "广东有岗", "本科友好"], pinned=True),
    S("haier", "海尔集团", "general", "家电", "集体企业", "家电/工业互联网",
      apply_url="https://campus.haier.net", official_site="https://www.haier.com",
      batch=["秋招", "春招"], status="未开启", positions=["电气工程师", "硬件研发", "设备"],
      cities=["青岛", "佛山", "武汉", "合肥"], deadline_note="预计2026年9月开启",
      salary_text="本科转月约 8-12k×13",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="家电全球化龙头（青岛）",
      ee_notes="青岛家电集群代表；电气研发/工厂电气均可投",
      tags=["S级对口"]),
    S("hisense", "海信集团", "general", "家电", "国企", "家电/显示",
      apply_url="https://campus.hisense.com", official_site="https://www.hisense.com",
      batch=["秋招", "春招"], status="未开启", positions=["电气工程师", "硬件研发", "电源"],
      cities=["青岛", "江门", "顺德"], deadline_note="预计2026年9月",
      salary_text="本科转月约 8-12k×13",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="电视/白电+光通信（青岛，广东有江门/顺德基地）",
      ee_notes="显示电源/电气研发对口；广东基地岗位留意",
      tags=["S级对口", "广东有岗"]),

    # ---------- 轨交 ----------
    S("crrc", "中国中车", "general", "轨交", "央企", "轨道交通装备",
      apply_url="https://campus.crrcgc.cc", official_site="https://www.crrcgc.cc",
      batch=["秋招", "春招", "社招"], status="未开启", positions=["电气设计", "牵引系统", "电机", "变流"],
      cities=["青岛", "株洲", "南京", "大连", "成都"], deadline_note="预计2026年9-10月，各子公司（四方/浦镇/大同等）分批",
      salary_text="本科转月约 8-12k×13，株洲所/四方效益好",
      salary_structure="基本工资+绩效+年终，五险二金，央企",
      desc="轨道交通装备全球龙头（高铁/地铁牵引电气系统）",
      ee_notes="牵引电气/电机/变流器研发核心对口电气；各子公司独立招聘，株洲所待遇最好（见单独条目）",
      tags=["S级对口", "央国企", "本科友好"], pinned=True),
    S("crrc-zelri", "中车株洲所", "general", "轨交", "央企", "牵引变流/新能源",
      alias="株洲所/中车时代电气", apply_url="https://campus.zelri.com", official_site="https://www.zelri.com",
      batch=["秋招", "春招", "实习"], status="未开启", positions=["电气研发", "变流器", "嵌入式", "算法", "风电"],
      cities=["株洲", "无锡", "常州"], deadline_note="预计2026年9月初开启（节奏早、竞争激烈）",
      salary_text="本科转月约 12-16k×(14-15)，年总包 18-28w",
      salary_structure="基本工资+绩效+年终（效益分红），五险二金",
      desc="中车最赚钱子公司（牵引变流+IGBT+风电+光伏），央企里的市场化标杆",
      ee_notes="电气/电力电子黄金雇主：变流器研发与电气专业高度对口；株洲成本低攒钱快；笔试重电力电子+电路",
      tags=["S级对口", "央国企", "本科友好"], pinned=True),
    S("guangzhou-metro", "广州地铁", "general", "轨交", "国企", "城市轨道交通",
      apply_url="https://campus.gz-mtr.com", official_site="https://www.gz-mtr.com",
      batch=["秋招", "春招"], status="未开启", positions=["供电系统", "电气工程师", "信号", "车辆电气"],
      cities=["广州"], deadline_note="预计2026年9-10月校招（与深圳地铁错峰）",
      salary_text="转正年总包约 12-16w，稳定性顶级",
      salary_structure="基本工资+安全绩效+年终，五险二金+补充医疗，国企福利标杆",
      desc="全国客流量最大地铁公司，供电/车辆岗位电气对口",
      ee_notes="供电系统岗位（变电/接触网/SCADA）是电气专属方向；广州国企稳定代表；本地院校有优势",
      tags=["S级对口", "广东有岗", "本科友好"], pinned=True),
    S("shenzhen-metro", "深圳地铁", "general", "轨交", "国企", "城市轨道交通",
      apply_url="https://campus.szmc.net", official_site="https://www.szmc.net",
      batch=["秋招", "春招"], status="未开启", positions=["供电", "车辆电气", "自动化"],
      cities=["深圳"], deadline_note="预计2026年9-11月，分批招聘",
      salary_text="转正年总包约 15-20w（深圳国企）",
      salary_structure="基本工资+绩效+年终，五险二金",
      desc="深圳国企，线路扩张期招聘量大",
      ee_notes="供电/车辆电气对口；深圳国企待遇+户口机会",
      tags=["S级对口", "广东有岗"], pinned=True),

    # ---------- 石化钢铁 ----------
    S("sinopec", "中国石化", "general", "石化钢铁", "央企", "石油化工",
      apply_url="https://job.sinopec.com", official_site="https://www.sinopecgroup.com",
      batch=["秋招", "春招", "社招"], status="未开启", positions=["电气工程师", "仪表", "设备", "炼化装置"],
      cities=["全国", "广东茂名/广州/湛江"], deadline_note="预计2026年9月下旬-10月全国统考（考行测+专业）",
      salary_text="转月约 8-12k+各类补贴，年总包 12-18w",
      salary_structure="基本工资+工龄/岗位/夜班补贴+年终，五险二金，央企福利天花板",
      desc="全球最大炼油公司，炼化厂电气/仪表需求稳定",
      ee_notes="电气自动化岗位遍布各炼化基地；茂名石化在广东湛江附近就业圈；统考模式认真准备行测",
      tags=["高度相关", "央国企", "本科友好"], pinned=True),
    S("cnpc", "中国石油", "general", "石化钢铁", "央企", "石油天然气",
      apply_url="https://zhaopin.cnpc.com.cn", official_site="https://www.cnpc.com.cn",
      batch=["秋招", "春招"], status="未开启", positions=["电气工程师", "自动化", "设备"],
      cities=["全国油田/炼厂"], deadline_note="预计2026年9月下旬-10月统考",
      salary_text="转月约 8-12k+补贴（油田驻地补贴高）",
      salary_structure="基本工资+各类补贴+年终，五险二金",
      desc="上游油气龙头，油田/管道/炼厂电气岗",
      ee_notes="油田多在偏远地区，待遇=工资+驻地补贴+稳定；适合能吃苦想去央企编的",
      tags=["高度相关", "央国企"]),
    S("cnooc", "中国海油", "general", "石化钢铁", "央企", "海上油气",
      apply_url="https://campus.cnooc.com", official_site="https://www.cnooc.com.cn",
      batch=["秋招"], status="未开启", positions=["电气工程师", "海洋平台电气", "设备"],
      cities=["深圳", "湛江", "天津", "惠州"], deadline_note="预计2026年9-10月，湛江/深圳分公司有基地",
      salary_text="转月约 10-15k+海上补贴，年总包 15-25w",
      salary_structure="基本工资+海上/驻地补贴+年终，五险二金，人均待遇央企前列",
      desc="海上油气龙头，南海东部/西部公司在深圳/湛江",
      ee_notes="广东学生地缘优势明显（湛江基地）；平台电气岗周期性驻海（28/28倒班），攒钱能力强",
      tags=["高度相关", "央国企", "广东有岗"], pinned=True),
    S("pipechina", "国家管网集团", "general", "石化钢铁", "央企", "油气管网",
      apply_url="https://zhaopin.pipechina.com.cn", official_site="https://www.pipechina.com.cn",
      batch=["秋招"], status="未开启", positions=["电气工程师", "站场设备", "自动化"],
      cities=["全国管道沿线", "广东区域公司"], deadline_note="预计2026年10-11月，2019年新组建央企",
      salary_text="转月约 9-13k，站场驻地补贴高",
      salary_structure="基本工资+驻地补贴+年终，五险二金",
      desc="全国油气主干管网运营商，站场电气是核心岗位",
      ee_notes="电气专业招录占比高（站场供配电/阀室）；站点多在沿线城市，广东区域公司在广州",
      tags=["S级对口", "央国企"]),
    S("baowu", "中国宝武", "general", "石化钢铁", "央企", "钢铁",
      apply_url="https://job.baowugroup.com", official_site="https://www.baowugroup.com",
      batch=["秋招"], status="未开启", positions=["电气工程师", "自动化", "设备管理"],
      cities=["上海", "湛江", "武汉", "马鞍山"], deadline_note="预计2026年9-10月",
      salary_text="转月约 9-13k，湛江钢铁效益好",
      salary_structure="基本工资+绩效+年终，五险二金",
      desc="全球最大钢企，湛江钢铁基地在广东",
      ee_notes="钢厂电气/自动化（PLC/传动）核心对口；湛江基地离家近待遇好，广东学生优选",
      tags=["S级对口", "央国企", "广东有岗"], pinned=True),
    S("hengli", "恒力石化", "general", "石化钢铁", "民企", "炼化/聚酯",
      apply_url="https://campus.hengli.com", official_site="https://www.henglipolymer.com",
      batch=["秋招"], status="未开启", positions=["电气工程师", "仪表", "设备"],
      cities=["大连", "苏州", "南通"], deadline_note="预计2026年9月",
      salary_text="本科转月约 9-12k×13",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="民营炼化一体化龙头（大连长兴岛）",
      ee_notes="民营大炼化薪资高于央企同岗；大连基地驻地",
      tags=["高度相关"]),

    # ---------- 半导体/面板 ----------
    S("smic", "中芯国际", "general", "半导体/面板", "国企", "晶圆代工",
      alias="SMIC", apply_url="https://campus.smics.com", official_site="https://www.smics.com",
      batch=["秋招", "春招", "实习"], status="未开启", positions=["厂务电气", "设备工程师", "动力系统", "自动化"],
      cities=["上海", "北京", "深圳", "天津"], deadline_note="预计2026年9月开启",
      salary_text="本科转月约 11-14k×(13-14)+倒班补贴",
      salary_structure="基本工资+绩效+年终+夜班/无尘室补贴，五险一金",
      desc="中国大陆晶圆代工龙头，扩产期厂务/设备需求大",
      ee_notes="电气对口厂务动力（供配电/特气/纯水）与设备岗；半导体制造业体系规范；深圳/上海基地",
      tags=["高度相关"], pinned=True),
    S("huahong", "华虹集团", "general", "半导体/面板", "国企", "晶圆代工",
      apply_url="https://campus.huahong.com", official_site="https://www.huahong.com.cn",
      batch=["秋招"], status="未开启", positions=["厂务电气", "设备", "动力"],
      cities=["上海", "无锡"], deadline_note="预计2026年9月",
      salary_text="本科转月约 10-13k×(13-14)",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="上海国资晶圆代工（特色工艺）",
      ee_notes="与中芯类似的厂务电气路径；上海+无锡双基地",
      tags=["高度相关"]),
    S("ymtc", "长江存储", "general", "半导体/面板", "国企", "存储芯片",
      alias="YMTC", apply_url="https://campus.ymtc.com", official_site="https://www.ymtc.com",
      batch=["秋招"], status="未开启", positions=["厂务电气", "设备工程师", "动力"],
      cities=["武汉"], deadline_note="预计2026年9月",
      salary_text="本科转月约 11-14k×(13-14)",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="NAND 闪存国产龙头（武汉光谷）",
      ee_notes="厂务动力电气岗需求稳定；武汉光谷生活成本友好",
      tags=["高度相关"]),
    S("cxmt", "长鑫存储", "general", "半导体/面板", "国企", "存储芯片",
      alias="CXMT", apply_url="https://campus.cxmt.com", official_site="https://www.cxmt.com",
      batch=["秋招"], status="未开启", positions=["厂务电气", "设备", "动力系统"],
      cities=["合肥", "北京"], deadline_note="预计2026年9月",
      salary_text="本科转月约 10-13k×(13-14)",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="DRAM 国产龙头（合肥）",
      ee_notes="合肥半导体双雄之一（另一个是国轩/蔚来）；厂务电气对口",
      tags=["高度相关"]),
    S("boe", "京东方", "general", "半导体/面板", "国企", "显示面板",
      alias="BOE", apply_url="https://campus.boe.com", official_site="https://www.boe.com",
      batch=["秋招", "春招"], status="未开启", positions=["电气工程师", "设备", "自动化", "厂务"],
      cities=["北京", "合肥", "成都", "福州", "绵阳"], deadline_note="预计2026年9月",
      salary_text="本科转月约 8-11k×13",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="全球LCD面板龙头，产线遍布多省",
      ee_notes="产线电气/自动化设备岗量大；多基地可就近选择",
      tags=["相关", "本科友好"]),

    # ---------- 高端制造 ----------
    S("sany", "三一集团", "general", "高端制造", "民企", "工程机械",
      apply_url="https://campus.sany.com.cn", official_site="https://www.sany.com.cn",
      batch=["秋招", "春招", "实习"], status="未开启", positions=["电气工程师", "硬件研发", "自动化", "电控"],
      cities=["长沙", "北京", "昆山", "珠海"], deadline_note="预计2026年8月底-9月开启（常提前抢人）",
      salary_text="本科转月约 9-13k×(13-14)",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="工程机械全球龙头，电动化转型期电控/电气需求爆发",
      ee_notes="工程机械电动化（电驱/电池包/电控）是电气新赛道；长沙总部，珠海有港口机械基地",
      tags=["S级对口"]),
    S("casc", "中国航天科技集团", "general", "高端制造", "央企", "航天/国防",
      alias="航天科技", apply_url="https://campus.spacechina.com", official_site="https://www.spacechina.com",
      batch=["秋招", "春招"], status="未开启", positions=["电气工程师", "供配电", "测发控", "硬件"],
      cities=["北京", "上海", "西安", "成都", "酒泉/文昌"], deadline_note="预计2026年9-11月，各院所分批（一院/五院/八院等）",
      salary_text="转月约 8-12k+驻地/保密补贴，总包不高但稳定",
      salary_structure="基本工资+绩效+补贴+年终，五险二金，事业编制感",
      desc="运载火箭/卫星国家队，各院所电气岗位稳定招录",
      ee_notes="电气供配电/测发控对口；院所多地北京上海；政审严格；适合追求稳定+家国情怀",
      tags=["高度相关", "央国企"]),
    S("cssc", "中国船舶集团", "general", "高端制造", "央企", "船舶/海洋装备",
      apply_url="https://campus.cssc.net.cn", official_site="https://www.cssc.net.cn",
      batch=["秋招"], status="未开启", positions=["电气工程师", "船舶电气", "自动化"],
      cities=["上海", "广州", "大连", "武汉"], deadline_note="预计2026年9-10月，各船厂/院所分批",
      salary_text="转月约 8-12k",
      salary_structure="基本工资+绩效+年终，五险二金",
      desc="全球最大造船集团（南北船合并），广州有龙穴基地",
      ee_notes="船舶电气系统（配电/推进/自动化）对口；广州黄埔/南沙有船厂",
      tags=["高度相关", "央国企", "广东有岗"]),
    S("cimc", "中集集团", "general", "高端制造", "合资", "集装箱/车辆/能化装备",
      alias="CIMC", apply_url="https://campus.cimc.com", official_site="https://www.cimc.com",
      batch=["秋招"], status="未开启", positions=["电气工程师", "自动化", "设备"],
      cities=["深圳", "东莞", "南通", "青岛"], deadline_note="预计2026年9月",
      salary_text="本科转月约 9-12k×13",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="集装箱全球龙头+能化/海工装备（深圳蛇口）",
      ee_notes="装备电气/自动化对口；深圳总部多元业务",
      tags=["相关", "广东有岗"]),
    S("galanz", "格兰仕集团", "general", "家电", "民企", "家电/微波炉",
      apply_url="https://campus.galanz.com", official_site="https://www.galanz.com",
      batch=["秋招", "春招", "实习"], status="进行中", positions=["电气工程师", "设备工程师", "自动化", "工艺"],
      cities=["佛山", "中山"], deadline_note="广海大就业网已发布其 2027 届校招公告（本站收件箱可见），基数大、投递早",
      salary_text="本科转月约 7-10k×13",
      salary_structure="基本工资+绩效+年终，五险一金，包食宿部分岗位",
      desc="微波炉/小家电全球龙头（佛山顺德+中山基地）",
      ee_notes="广东制造就业大户，工厂电气/自动化设备岗量大，本科友好；从就业网公告直接投",
      tags=["高度相关", "广东有岗", "本科友好"]),
    S("tcl", "TCL科技/TCL实业", "general", "半导体/面板", "民企", "显示/家电/光伏",
      alias="TCL集团", apply_url="https://campus.tcl.com", official_site="https://www.tcl.com",
      batch=["秋招", "春招", "实习"], status="未开启", positions=["电气工程师", "设备工程师", "厂务", "硬件"],
      cities=["惠州", "深圳", "武汉", "广州"], deadline_note="预计2026年9月开启（TCL中环/华星等子公司分批）",
      salary_text="本科转月约 8-12k×(13-14)",
      salary_structure="基本工资+绩效+年终，五险一金，上市公司",
      desc="面板（华星光电）+ 光伏硅片（中环）+ 家电多元集团，惠州大本营",
      ee_notes="面板厂电气/厂务/设备岗量大；惠州总部离家近选项",
      tags=["高度相关", "广东有岗", "本科友好"]),
    S("cetc", "中国电子科技集团", "general", "高端制造", "央企", "军工电子/雷达",
      alias="CETC/电科", apply_url="https://campus.cetc.com.cn", official_site="https://www.cetc.com.cn",
      batch=["秋招", "春招"], status="未开启", positions=["电气工程师", "电源", "硬件", "供配电"],
      cities=["北京", "南京", "成都", "合肥", "广州（七所）"], deadline_note="预计2026年9-11月，各研究所分批招聘（14所/29所/38所/七所等）",
      salary_text="转月约 8-12k+驻地/保密补贴，总包不高但极稳",
      salary_structure="基本工资+绩效+补贴+年终，五险二金，事业编制感",
      desc="军工电子国家队，数十家研究所遍布全国（广东有七所/七research）",
      ee_notes="电气供配电/电源硬件对口研究所岗位；政审严格，户籍城市匹配优先",
      tags=["高度相关", "央国企"]),
    S("comac", "中国商飞", "general", "高端制造", "央企", "大飞机",
      apply_url="https://campus.comac.cc", official_site="https://www.comac.cc",
      batch=["秋招"], status="未开启", positions=["电气系统设计", "飞机电气", "工艺", "试飞保障"],
      cities=["上海", "东营", "南昌"], deadline_note="预计2026年9-10月",
      salary_text="转月约 10-14k",
      salary_structure="基本工资+绩效+年终，五险二金",
      desc="C919 大飞机研制主体（上海总装）",
      ee_notes="飞机电气系统研发对口；国产大飞机叙事+上海户口机会",
      tags=["高度相关", "央国企"]),
    S("xcmg", "徐工集团", "general", "高端制造", "国企", "工程机械",
      alias="XCMG", apply_url="https://campus.xcmg.com", official_site="https://www.xcmg.com",
      batch=["秋招", "春招"], status="未开启", positions=["电气工程师", "电控研发", "设备"],
      cities=["徐州"], deadline_note="预计2026年8月底-9月开启",
      salary_text="本科转月约 9-12k×13",
      salary_structure="基本工资+绩效+年终，五险一金+企业年金",
      desc="全球工程机械前三（徐州），电动化转型电控需求大",
      ee_notes="工程机械电动化（电驱/电池管理）是电气新增长点；徐州成本洼地",
      tags=["S级对口", "央国企"]),
    S("weichai", "潍柴动力", "general", "高端制造", "国企", "发动机/新能源动力",
      apply_url="https://campus.weichai.com", official_site="https://www.weichai.com",
      batch=["秋招"], status="未开启", positions=["电气工程师", "电控", "测试", "新能源动力"],
      cities=["潍坊", "西安", "扬州"], deadline_note="预计2026年9月",
      salary_text="本科转月约 9-12k×13",
      salary_structure="基本工资+绩效+年终，五险一金，山东国企待遇前列",
      desc="柴油发动机龙头 + 氢燃料/混动动力总成（潍坊）",
      ee_notes="动力电控/测试电气对口；谭旭光时代待遇在山东国企里口碑好",
      tags=["高度相关", "央国企"]),
    S("gwm", "长城汽车", "general", "高端制造", "民企", "整车",
      apply_url="https://campus.gwm.com.cn", official_site="https://www.gwm.com.cn",
      batch=["秋招", "春招", "实习"], status="未开启", positions=["电气系统", "三电", "制造", "测试"],
      cities=["保定", "重庆永川", "泰州", "日照"], deadline_note="预计2026年9月开启",
      salary_text="本科转月约 9-13k×(13-14)",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="民营整车龙头之一（保定总部），新能源转型加速",
      ee_notes="整车电气/三电岗位需求大；保定生活成本极低，性价比路线",
      tags=["S级对口"]),
    S("chery", "奇瑞控股", "general", "高端制造", "国企", "整车",
      apply_url="https://campus.chery.cn", official_site="https://www.chery.cn",
      batch=["秋招", "春招"], status="未开启", positions=["电气系统", "三电", "设备", "测试"],
      cities=["芜湖", "大连", "青岛"], deadline_note="预计2026年9月开启（出口强势，招人多）",
      salary_text="本科转月约 9-13k×(13-14)",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="出口第一自主品牌（芜湖），混动/纯电双线放量",
      ee_notes="销量扩张期电气岗位供给大；芜湖宜居成本低",
      tags=["S级对口", "央国企"]),
    S("goertek", "歌尔股份", "general", "ICT硬件", "民企", "声学/VR/可穿戴",
      apply_url="https://campus.goertek.com", official_site="https://www.goertek.com",
      batch=["秋招"], status="未开启", positions=["电气工程师", "硬件研发", "自动化设备", "测试"],
      cities=["潍坊", "青岛", "深圳"], deadline_note="预计2026年9月",
      salary_text="本科转月约 8-11k×13",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="声学器件+VR代工龙头（潍坊总部）",
      ee_notes="消费电子设备/电气岗量大；潍坊成本低，AI 硬件浪潮受益者",
      tags=["相关", "本科友好"]),
    S("wanhua", "万华化学", "general", "石化钢铁", "国企", "化工新材料",
      apply_url="https://campus.whchem.com", official_site="https://www.whchem.com",
      batch=["秋招"], status="未开启", positions=["电气工程师", "仪表工程师", "设备管理"],
      cities=["烟台", "宁波", "四川眉山"], deadline_note="预计2026年9-10月",
      salary_text="转月约 11-15k×13+项目奖，化工央企混改标杆",
      salary_structure="基本工资+绩效+年终（效益极好），五险二金+补充公积金",
      desc="全球 MDI 龙头、化工界华为（烟台）",
      ee_notes="化工大厂电气/仪表岗位规范且高薪；烟台基地为主，待遇在化工圈第一档",
      tags=["高度相关", "央国企"]),
    S("hymson", "海目星激光", "general", "高端制造", "民企", "激光设备",
      apply_url="https://campus.hymson.com", official_site="https://www.hymson.com",
      batch=["秋招"], status="未开启", positions=["电气工程师", "电控设计", "调试工程师"],
      cities=["深圳", "常州", "江门"], deadline_note="预计2026年9月",
      salary_text="本科转月约 9-13k×13",
      salary_structure="基本工资+绩效+项目奖，五险一金",
      desc="锂电/光伏激光及自动化设备商（深圳总部，常州/江门基地）",
      ee_notes="非标自动化设备的电气设计（PLC/伺服/电柜）岗位大户；江门基地离家近",
      tags=["S级对口", "广东有岗", "本科友好"]),
    S("hanslaser", "大族激光", "general", "高端制造", "民企", "激光装备",
      apply_url="https://campus.hanslaser.com", official_site="https://www.hanslaser.com",
      batch=["秋招"], status="未开启", positions=["电气工程师", "电控", "调试", "硬件"],
      cities=["深圳", "苏州", "成都"], deadline_note="预计2026年9月",
      salary_text="本科转月约 9-13k×13",
      salary_structure="基本工资+绩效+年终，五险一金，上市公司",
      desc="激光装备亚洲龙头（深圳），设备线体电气岗位多",
      ee_notes="非标设备电气设计岗量大的老牌设备商；深圳宝安总部",
      tags=["S级对口", "广东有岗", "本科友好"]),
    S("wuxi-lead", "先导智能", "general", "高端制造", "民企", "锂电/光伏智能装备",
      alias="Wuxi Lead", apply_url="https://campus.leadintel.com", official_site="https://www.leadintel.com",
      batch=["秋招"], status="未开启", positions=["电气工程师", "电控设计", "PLC工程师", "调试"],
      cities=["无锡", "深圳", "珠海"], deadline_note="预计2026年9月（锂电设备扩产周期回归）",
      salary_text="本科转月约 9-13k×13+项目奖",
      salary_structure="基本工资+绩效+项目奖金，五险一金",
      desc="全球锂电智能装备龙头（无锡），宁德/比亚迪产线供应商",
      ee_notes="锂电设备电气/PLC/调试岗是电气就业大户中的大户，本科友好；出差多但攒钱快",
      tags=["S级对口", "本科友好"], pinned=True),
]
