# -*- coding: utf-8 -*-
"""电网/发电/设计院方向种子数据（33 家）。薪资均为公开渠道聚合口径，仅供参考。"""
from .helpers import S
from .verify import VERIFIED_DATE

COMPANIES = [
    # ---------- 电网 ----------
    S("sgcc", "国家电网", "grid", "电网", "央企", "电力公用事业",
      alias="国网", apply_url="https://zhaopin.sgcc.com.cn", official_site="https://www.sgcc.com.cn",
      batch=["秋招", "春招", "实习"], status="未开启", positions=["电气类", "变电运维", "输电线路", "继电保护", "营销服务", "调度"],
      cities=["全国27个省公司"], start_date=None, deadline=None,
      deadline_note="2027届一批预计2026年10月报名（往年中旬截止）、12月考试；二批约2027年3月",
      salary_text="转正月综合约 8-15k（省间差异大，江浙京津冀鲁等偏高）",
      salary_structure="基本工资+岗位绩效+津贴+年终奖，五险二金（含企业年金），央企编制感强",
      desc="全球最大公用事业企业，27个省公司统一平台招聘，电气就业基本盘",
      ee_notes="电气最主渠道。笔试约80%电工类专业课（电路/电机/电分/继保/高压/电气设备）+20%综合能力；分省报名分省录取，本科可报大部分省公司；等级证书、应届身份卡得严",
      tags=["S级对口", "央国企", "本科友好"], pinned=True),
    S("csg", "南方电网", "grid", "电网", "央企", "电力公用事业",
      alias="南网（含广东电网）", apply_url="https://zhaopin.csg.cn", official_site="https://www.csg.cn",
      batch=["秋招", "春招", "实习"], status="未开启", positions=["电气类", "变电运维", "配电", "继电保护", "营销", "信息通信"],
      cities=["广东（各地市含湛江/茂名/阳江供电局）", "广西", "云南", "贵州", "海南"], deadline_note="2027届一批预计2026年9月下旬-10月报名；广东电网各地市局同步招聘",
      salary_text="广东电网转正年总包约 12-20w（珠三角高于粤东西北），深圳供电局更高",
      salary_structure="基本工资+绩效+岗位津贴+年终，五险二金+企业年金，福利完善",
      desc="广东电气就业性价比首选，广东电网招聘量极大，广海大地缘优势明显",
      ee_notes="广东电气生重点目标。统一平台报名（广东/广西/云南/贵州/海南五省区+深圳供电局）；笔试专业课+行测；地市局对本科电气友好；湛茂阳地区竞争小于珠三角",
      tags=["S级对口", "央国企", "广东有岗", "本科友好"], pinned=True),
    S("csg-sz", "深圳供电局", "grid", "电网", "央企", "电力公用事业",
      alias="南网深圳局", apply_url="https://zhaopin.csg.cn", official_site="https://www.csg.cn",
      batch=["秋招", "春招"], status="未开启", positions=["电气类", "变电", "配电", "营销"],
      cities=["深圳"], deadline_note="经南方电网统一平台报名，时间与南网一批一致（约9-10月）",
      salary_text="转正年总包约 20-30w（深圳央企天花板级）",
      salary_structure="基本工资+绩效+年终，五险二金，深圳户口/公租房支持",
      desc="南方电网直属局，待遇广东电网体系内最高档",
      ee_notes="与南网同一平台报名，志愿里单列；竞争激烈，硕士为主，电气顶尖本科生也有机会",
      tags=["S级对口", "央国企", "广东有岗"], pinned=True),
    S("csg-esp", "南网储能", "grid", "电网", "央企", "抽水蓄能/新型储能",
      alias="调峰调频公司", apply_url="https://zhaopin.csg.cn", official_site="https://www.csg.cn",
      batch=["秋招", "春招"], status="未开启", positions=["电气类", "水机/水动", "自动化"],
      cities=["广东", "云南", "贵州"], deadline_note="随南方电网统一招聘（约9-10月），部分岗位单招",
      salary_text="转正年总包约 12-18w",
      salary_structure="南网体系薪酬制度，五险二金，站区偏远有补贴",
      desc="南网旗下抽水蓄能+新型储能平台，电站多在粤北/云贵",
      ee_notes="电气+水动+自动化对口；工作地点多为山区电站，适合能接受驻站的求职者",
      tags=["S级对口", "央国企", "广东有岗"]),
    S("csg-digital", "南网数字集团", "grid", "电网", "央企", "电力信息化",
      alias="南网数研院", apply_url="https://zhaopin.csg.cn", official_site="https://www.csg.cn",
      batch=["秋招", "春招"], status="未开启", positions=["电气信息化", "软件开发", "数据", "自动化"],
      cities=["广州"], deadline_note="南网统一招聘或单招（约9-10月）",
      salary_text="转正年总包约 15-22w（广州）",
      salary_structure="南网体系+市场化绩效，五险二金",
      desc="南网数字化转型主力，坐标广州，电气+计算机复合背景吃香",
      ee_notes="电气信息类/自动化可投，软件开发岗竞争接近互联网；懂电力的程序员稀缺",
      tags=["高度相关", "央国企", "广东有岗"]),
    S("csg-tech", "南网科技", "grid", "电网", "央企", "电力科技/试验检测",
      apply_url="https://zhaopin.csg.cn", official_site="https://www.csg.cn",
      batch=["秋招", "春招"], status="未开启", positions=["电气试验", "储能", "检测", "研发"],
      cities=["广州"], deadline_note="约9-10月，随南网统一招聘",
      salary_text="转正年总包约 14-20w",
      salary_structure="南网体系薪酬，五险二金+项目绩效",
      desc="南网旗下上市科技公司，电源侧试验检测+储能方向",
      ee_notes="电气工程直接对口；研发岗偏好硕士，试验检测岗本科可投",
      tags=["S级对口", "央国企", "广东有岗"]),

    # ---------- 发电集团 ----------
    S("chng", "中国华能", "grid", "发电集团", "央企", "发电",
      alias="华能集团", apply_url="https://campus.chng.com.cn", official_site="https://www.chng.com.cn",
      batch=["秋招", "春招", "社招"], status="未开启", positions=["电气运行", "检修", "集控", "新能源场站"],
      cities=["全国", "广东汕头/海门"], deadline_note="2027届秋招预计2026年9月底-11月分批报名",
      salary_text="转月约 8-12k×13，电厂效益不同有浮动",
      salary_structure="基本工资+绩效+运行补贴+年终，五险二金，包食宿常见",
      desc="五大发电之首，火电/水电/新能源基地遍布全国",
      ee_notes="电气运行/集控岗位大量招电气本科；电厂多在郊区，接受驻地是前提；总部/研究院门槛硕士+",
      tags=["S级对口", "央国企", "本科友好"]),
    S("datang", "中国大唐", "grid", "发电集团", "央企", "发电",
      apply_url="https://campus.dt-china.com", official_site="https://www.cdtr.com.cn",
      batch=["秋招", "春招"], status="未开启", positions=["电气运行", "检修", "新能源"],
      cities=["全国"], deadline_note="预计2026年9月底-11月报名（以集团招聘公告为准）",
      salary_text="转月约 8-11k×13",
      salary_structure="基本工资+绩效+补贴+年终，五险二金",
      desc="五大发电集团之一，火电转型新能源加速",
      ee_notes="招录节奏与华能/华电类似，电气运行岗为主；部分省公司单独发布，注意官网+省公司公告",
      tags=["S级对口", "央国企", "本科友好"]),
    S("huadian", "中国华电", "grid", "发电集团", "央企", "发电",
      apply_url="https://job.chd.com.cn", official_site="https://www.chd.com.cn",
      batch=["秋招", "春招"], status="未开启", positions=["电气运行", "检修", "水电", "新能源"],
      cities=["全国", "广东梅州/清远"], deadline_note="预计2026年9月底-11月报名",
      salary_text="转月约 8-11k×13",
      salary_structure="基本工资+绩效+补贴+年终，五险二金",
      desc="五大发电集团之一，水电板块（乌江/金沙江）规模大",
      ee_notes="广东有梅州/清远等电厂；水电站在偏远山区，待遇含驻地补贴",
      tags=["S级对口", "央国企", "本科友好"]),
    S("chnenergy", "国家能源集团", "grid", "发电集团", "央企", "煤电一体化",
      alias="国能投", apply_url="https://zhaopin.chnenergy.com.cn", official_site="https://www.ceic.com",
      batch=["秋招", "春招"], status="未开启", positions=["电气运行", "集控", "检修", "矿电气"],
      cities=["全国"], deadline_note="预计2026年10月-11月报名，全国统考",
      salary_text="转月约 8-12k×13，西部矿区补贴高",
      salary_structure="基本工资+绩效+津补贴+年终，五险二金",
      desc="全球最大煤炭+发电一体化央企（原国电+神华）",
      ee_notes="统考模式（类似国网，考专业课+行测）；火电/矿井电气岗需求大，接受矿区驻地可冲",
      tags=["S级对口", "央国企", "本科友好"]),
    S("spic", "国家电投", "grid", "发电集团", "央企", "发电/核电/新能源",
      alias="国电投", apply_url="https://zhaopin.spic.com.cn", official_site="https://www.spic.com.cn",
      batch=["秋招", "春招"], status="未开启", positions=["电气运行", "新能源", "核电", "综合能源"],
      cities=["全国"], deadline_note="预计2026年9月底-11月分子公司分批报名；网申走国聘专区（域名按届更新，以官网公告为准）",
      salary_text="转月约 8-12k×13，核电/海上风电板块更高",
      salary_structure="基本工资+绩效+补贴+年终，五险二金",
      desc="五大发电中新能源装机最大，绿电转型最激进",
      ee_notes="各二级单位自主招聘节奏不一，需盯集团招聘平台+子公司公众号；新能源场站电气岗多",
      tags=["S级对口", "央国企", "本科友好"]),
    S("sdic", "国投电力", "grid", "发电集团", "央企", "水火电/新能源",
      alias="国投集团电力板块", apply_url="https://zhaopin.sdic.com.cn", official_site="https://www.sdicpower.com",
      batch=["秋招", "春招"], status="未开启", positions=["电气运行", "水电站", "新能源"],
      cities=["全国", "云南/四川/广西"], deadline_note="预计2026年9-11月，分子公司分批",
      salary_text="转月约 9-12k×13，雅砻江水电效益好",
      salary_structure="基本工资+绩效+驻地补贴+年终，五险二金",
      desc="国投集团旗下电力平台，控股雅砻江水电（两河口/锦屏）",
      ee_notes="水电站电气岗对口；电站地处川滇，驻站补贴可观，适合追求稳定+攒钱",
      tags=["S级对口", "央国企"]),
    S("cr-power", "华润电力", "grid", "发电集团", "央企", "火电/新能源",
      apply_url="https://crc.ewozi.com", official_site="https://www.crpower.com",
      batch=["秋招", "春招"], status="未开启", positions=["电气运行", "检修", "风电/光伏运营"],
      cities=["全国", "广东广州/惠州"], deadline_note="预计2026年9-10月，走华润集团统一校招渠道",
      salary_text="转月约 9-13k×13，华南区域效益好",
      salary_structure="基本工资+绩效+年终，五险一金+企业年金，市场化程度高",
      desc="华润集团旗下，火电+新能源运营质量行业前列",
      ee_notes="央企控股市场化运作，薪酬在发电圈口碑好；华南区域岗位多",
      tags=["S级对口", "央国企", "广东有岗"]),
    S("jingneng", "京能集团", "grid", "发电集团", "国企", "热电/新能源",
      apply_url="https://zhaopin.powerbeijing.com", official_site="https://www.powerbeijing.com",
      batch=["秋招"], status="未开启", positions=["电气运行", "热控", "新能源"],
      cities=["北京", "内蒙古/宁夏基地"], deadline_note="预计2026年9-10月",
      salary_text="转月约 9-12k，北京户口概率大",
      salary_structure="北京市属国企薪酬体系，五险二金",
      desc="北京市属能源国企，热电联产+风光基地",
      ee_notes="北京国企户口优势；外地基地驻站为主",
      tags=["S级对口", "央国企"]),
    S("zheneng", "浙能集团", "grid", "发电集团", "国企", "综合能源",
      apply_url="https://campus.zjenergy.com.cn", official_site="https://www.zjenergy.com.cn",
      batch=["秋招"], status="未开启", positions=["电气运行", "检修", "新能源"],
      cities=["浙江"], deadline_note="预计2026年9-10月",
      salary_text="转月约 10-14k，浙江国企待遇优",
      salary_structure="基本工资+绩效+年终，五险二金",
      desc="浙江省属能源龙头，发电装机省内最大",
      ee_notes="省属国企里待遇第一梯队；浙江能源岗位竞争激烈，省内院校有地缘优势",
      tags=["S级对口", "央国企"]),
    S("shenergy", "申能集团", "grid", "发电集团", "国企", "电力/燃气",
      apply_url="https://campus.shenergy.com.cn", official_site="https://www.shenergy.com.cn",
      batch=["秋招"], status="未开启", positions=["电气运行", "检修", "新能源"],
      cities=["上海"], deadline_note="预计2026年9-10月",
      salary_text="转月约 10-14k，上海国企",
      salary_structure="基本工资+绩效+年终，五险二金+补充公积金",
      desc="上海市属综合能源集团（电力+燃气双主业）",
      ee_notes="上海国企户口/稳定性佳；外高桥/临港电厂电气岗对口",
      tags=["S级对口", "央国企"]),

    S("ctg", "中国三峡集团", "grid", "发电集团", "央企", "水电/新能源",
      alias="三峡集团", apply_url="https://chrcmp.chinahr.com/pages/sanxia/", official_site="https://www.ctg.com.cn",
      batch=["秋招", "春招"], status="未开启", positions=["电气运行", "水电站", "新能源", "抽水蓄能"],
      cities=["宜昌", "北京", "成都", "全国电站"], deadline_note="预计2026年9月中-10月报名（投递走中华英才网托管专区，当前批次显示已结束属正常，新一届开启后恢复）",
      salary_text="转月约 9-13k×13，长江电力/三峡能源效益好",
      salary_structure="基本工资+绩效+年终，五险二金，上市公司体系",
      desc="水电航母（三峡/白鹤滩/乌东德），旗下长江电力是全球最大水电上市公司",
      ee_notes="水电站电气运行核心对口；旗下长江电力（上市）待遇在发电圈第一梯队；投递通道为集团统一专区",
      tags=["S级对口", "央国企"], pinned=True),

    # ---------- 核电 ----------
    S("cgn", "中广核", "grid", "核电", "央企", "核电/清洁能源",
      alias="中国广核集团", apply_url="https://campus.cgnpc.com.cn", official_site="https://www.cgn.com.cn",
      batch=["秋招", "春招", "实习"], status="未开启", positions=["电气", "核岛/常规岛", "仪控", "运行"],
      cities=["深圳", "大亚湾/阳江/台山/防城港等基地"], deadline_note="「启明星」校招预计2026年9月初开启，招满即止",
      salary_text="首年总包约 15-20w（含各类补贴），基地驻地补贴高",
      salary_structure="基本工资+绩效+驻地/核岗位补贴+年终，五险二金+补充医疗",
      desc="全球在运装机前三的清洁能源集团，核电大雇主",
      ee_notes="电气/自动化/机械均大量招；本科可投运行/维修/电气岗；基地偏远但攒钱；体检+政审严格",
      tags=["S级对口", "央国企", "本科友好", "广东有岗"], pinned=True),
    S("cnnc", "中核集团", "grid", "核电", "央企", "核电/核燃料",
      alias="中国核工业集团", apply_url="https://hr.cnnc.com.cn", official_site="https://www.cnnc.com.cn",
      batch=["秋招", "春招"], status="未开启", positions=["电气", "运行", "仪控", "检修"],
      cities=["全国", "福建/海南/江苏/浙江基地"], deadline_note="预计2026年9月起各单位分批招聘",
      salary_text="首年总包约 12-18w（基地差异大）",
      salary_structure="基本工资+绩效+核岗位补贴+年终，五险二金",
      desc="核电+核燃料+核技术全产业链央企（秦山/福清/昌江等）",
      ee_notes="「中核招聘」平台统一投递；电气运行/电气维修岗本科可投；涉密岗位政审严格",
      tags=["S级对口", "央国企", "本科友好"]),

    # ---------- 地方能源 ----------
    S("gpg", "广东省能源集团", "grid", "地方能源", "国企", "电力/天然气/新能源",
      alias="粤电集团", apply_url="https://campus.gdyd.com", official_site="https://www.gdyd.com",
      batch=["秋招", "春招"], status="未开启", positions=["电气运行", "检修", "新能源场站", "集控"],
      cities=["广东省内多市（含茂名/湛江区域电厂）"], deadline_note="预计2026年9-10月校招，关注「广东能源集团」公告",
      salary_text="转月约 9-13k×13，年总包约 13-18w",
      salary_structure="基本工资+绩效+运行津贴+年终，五险二金，广东省属国企待遇标杆",
      desc="广东省属最大能源集团（原粤电），省内电厂遍布",
      ee_notes="广东电气生本地优选；竞争小于南网；珠三角电厂（珠海/湛江生物质等）驻地有补贴",
      tags=["S级对口", "央国企", "广东有岗", "本科友好"], pinned=True),
    S("sec", "深圳能源", "grid", "地方能源", "国企", "电力/燃气/环保",
      apply_url="https://campus.sec.com.cn", official_site="https://www.sec.com.cn",
      batch=["秋招", "春招"], status="未开启", positions=["电气运行", "检修", "环保电厂"],
      cities=["深圳", "东莞/潮州等"], deadline_note="预计2026年9-11月",
      salary_text="转月约 10-14k，年总包约 15-20w",
      salary_structure="基本工资+绩效+年终，五险二金，深圳市属国企",
      desc="深圳市属综合能源上市公司（妈湾/东部电厂等）",
      ee_notes="深圳国企待遇好+离家近双重优势；垃圾焚烧电厂电气岗也常年招",
      tags=["S级对口", "央国企", "广东有岗"], pinned=True),

    # ---------- 设计院/工程 ----------
    S("powerchina", "中国电建", "grid", "设计院", "央企", "电力工程/基建",
      apply_url="https://campus.powerchina.cn", official_site="https://powerchina.cn",
      batch=["秋招", "春招", "社招"], status="未开启", positions=["电气一次/二次设计", "现场电气工程师", "机电"],
      cities=["全国+海外项目"], deadline_note="集团统一校招平台预计2026年9月开启，各工程局/设计院分批",
      salary_text="转月约 7-11k，海外项目补贴可达 2-3 倍",
      salary_structure="基本工资+项目补贴+绩效+年终，五险二金，驻项目现场",
      desc="全球电力建设最大承包商（水电/新能源EPC），下属设计院+工程局众多",
      ee_notes="电气设计岗（设计院）与现场电气工程师（工程局）路径差异大：设计院坐办公室，工程局常驻工地；能接受海外派遣者回报高",
      tags=["S级对口", "央国企", "本科友好"]),
    S("ceec", "中国能建", "grid", "设计院", "央企", "电力工程/基建",
      apply_url="https://job.ceec.net.cn", official_site="https://www.ceec.net.cn",
      batch=["秋招", "春招", "社招"], status="未开启", positions=["电气设计", "调试", "EPC管理"],
      cities=["全国+海外"], deadline_note="预计2026年9月起各子公司分批，集团平台统一入口",
      salary_text="转月约 7-11k，项目补贴另计",
      salary_structure="基本工资+项目绩效+补贴+年终，五险二金",
      desc="电力设计国家队（原电规总院系），下辖六大区设计院+葛洲坝",
      ee_notes="省级电力设计院（如广东省电力设计研究院GEDI）属能建体系，电气设计岗核心去处；投递时按子公司报",
      tags=["S级对口", "央国企", "本科友好"]),
    S("gzcb", "中国葛洲坝集团", "grid", "设计院", "央企", "水利水电/基建",
      apply_url="https://campus.ceec.net.cn", official_site="https://www.ccccltd.cn",
      batch=["秋招", "春招"], status="未开启", positions=["电气工程师", "机电安装", "项目管理"],
      cities=["全国+海外"], deadline_note="随中国能建统一校招（约9月起）",
      salary_text="转月约 7-10k+项目补贴",
      salary_structure="基本工资+项目绩效+补贴，五险二金",
      desc="水利水电施工龙头，能建旗下工程板块",
      ee_notes="机电安装/现场电气岗大量招电气本科；工地节奏强，回报与驻地补贴挂钩",
      tags=["S级对口", "央国企", "本科友好"]),
    S("gedi", "广东省电力设计研究院", "grid", "设计院", "央企", "电力设计",
      alias="GEDI/中能建广东院", apply_url="https://campus.ceec.net.cn", official_site="https://www.gedi.com.cn",
      batch=["秋招"], status="未开启", positions=["电气一次设计", "电气二次设计", "新能源设计", "数字化"],
      cities=["广州"], deadline_note="预计2026年9-10月单独或随能建平台招聘",
      salary_text="转正年总包约 15-25w（广州设计院天花板级）",
      salary_structure="基本工资+项目奖金+年终，五险二金，效益稳定",
      desc="华南电力设计龙头，承接广东大量电源/电网EPC设计",
      ee_notes="电气设计岗首选之一；近年门槛以硕士为主，本科需表现突出；奖金与项目量挂钩",
      tags=["S级对口", "央国企", "广东有岗"], pinned=True),
    S("csedi", "中南电力设计院", "grid", "设计院", "央企", "电力设计",
      apply_url="https://campus.ceec.net.cn", official_site="https://www.csepdi.com",
      batch=["秋招"], status="未开启", positions=["电气设计", "输电线路设计", "新能源设计"],
      cities=["武汉"], deadline_note="预计2026年9-10月",
      salary_text="转正年总包约 12-18w",
      salary_structure="基本工资+项目奖金+年终，五险二金",
      desc="华中电力设计龙头（能建系）",
      ee_notes="电气/输电线路设计对口；武汉性价比高，硕士为主",
      tags=["S级对口", "央国企"]),
    S("ecidi", "华东勘测设计研究院", "grid", "设计院", "央企", "水电/新能源设计",
      alias="华东院（电建系）", apply_url="https://campus.powerchina.cn", official_site="https://www.ecidi.com",
      batch=["秋招"], status="未开启", positions=["电气设计", "抽蓄机电", "智慧工程"],
      cities=["杭州"], deadline_note="预计2026年9-10月",
      salary_text="转正年总包约 14-20w",
      salary_structure="基本工资+项目奖金+年终，五险二金",
      desc="水电/抽蓄设计第一梯队（电建系），数字化程度高",
      ee_notes="抽水蓄能大发展周期，机电/电气设计需求旺；杭州安家好选择",
      tags=["S级对口", "央国企"]),
    S("nwindi", "西北勘测设计研究院", "grid", "设计院", "央企", "水电/新能源设计",
      alias="西北院（电建系）", apply_url="https://campus.powerchina.cn", official_site="https://www.nwindi.com",
      batch=["秋招"], status="未开启", positions=["电气设计", "新能源规划", "机电"],
      cities=["西安"], deadline_note="预计2026年9-10月",
      salary_text="转正年总包约 12-16w",
      salary_structure="基本工资+项目奖金+年终，五险二金",
      desc="西北水电/风光基地设计主力（电建系）",
      ee_notes="大型风光基地+抽蓄设计需求稳定；西安生活成本低，性价比可以",
      tags=["S级对口", "央国企"]),
    S("npdi", "华北电力设计院", "grid", "设计院", "央企", "电力设计",
      alias="华北院（能建系）", apply_url="https://campus.ceec.net.cn", official_site="https://www.ncpe.com.cn",
      batch=["秋招"], status="未开启", positions=["电气设计", "系统规划"],
      cities=["北京"], deadline_note="预计2026年9-10月",
      salary_text="转正年总包约 14-20w",
      salary_structure="基本工资+项目奖金+年终，五险二金",
      desc="北京四大电力设计院之一（能建系）",
      ee_notes="北京户口机会+设计院稳定收益；硕士为主",
      tags=["S级对口", "央国企"]),
    S("swedi", "西南电力设计院", "grid", "设计院", "央企", "电力设计",
      alias="西南院（能建系）", apply_url="https://campus.ceec.net.cn", official_site="https://www.swedi.com.cn",
      batch=["秋招"], status="未开启", positions=["电气设计", "线路设计"],
      cities=["成都"], deadline_note="预计2026年9-10月",
      salary_text="转正年总包约 12-17w",
      salary_structure="基本工资+项目奖金+年终，五险二金",
      desc="川渝电力设计龙头（能建系）",
      ee_notes="成都宜居+设计院稳定，电气设计对口；硕士优先但本科可投部分岗位",
      tags=["S级对口", "央国企"]),
    S("yangtze-power", "长江电力", "grid", "发电集团", "央企", "水力发电",
      alias="三峡集团长江电力", apply_url="https://chrcmp.chinahr.com/pages/sanxia/", official_site="https://www.cypc.com.cn",
      batch=["秋招", "春招"], status="未开启", positions=["电气运行", "水电站机电", "检修", "调度"],
      cities=["宜昌", "全国六座梯级电站（含溪洛渡/向家坝/乌东德）"], last_verified=VERIFIED_DATE,
      verify_note="随三峡集团校招专区统一报名（专区入口已核验）",
      deadline_note="预计2026年9月中-10月，随三峡集团统一校招",
      salary_text="首年总包约 15-20w，水电现金牛待遇发电圈第一梯队",
      salary_structure="基本工资+绩效+年终（效益极好），五险二金+企业年金",
      desc="全球最大水电上市公司（三峡/葛洲坝/溪洛渡/向家坝/乌东德/白鹤滩六座梯级电站）",
      ee_notes="水电站电气运行天花板级雇主；待遇好但电站地处鄂川滇，接受驻地是前提；走三峡集团专区报名",
      tags=["S级对口", "央国企"], pinned=True),
    S("ctg-re", "三峡能源", "grid", "发电集团", "央企", "风电/光伏",
      alias="三峡新能源", apply_url="https://chrcmp.chinahr.com/pages/sanxia/", official_site="https://www.ctg.com.cn",
      batch=["秋招", "春招"], status="未开启", positions=["电气运行", "风电/光伏场站", "海上风电", "检修"],
      cities=["北京", "江苏", "广东阳江等海上风电基地", "全国场站"], last_verified=VERIFIED_DATE,
      verify_note="随三峡集团校招专区统一报名（专区入口已核验）",
      deadline_note="预计2026年9月中-10月，随三峡集团统一校招",
      salary_text="转月约 9-13k×13，海上风电项目补贴高",
      salary_structure="基本工资+绩效+项目补贴+年终，五险二金",
      desc="三峡集团新能源上市平台，海上风电装机全国前列",
      ee_notes="海上风电场站电气运行/检修对口；阳江沙扒等粤西海风项目集中，广东学生重点留意",
      tags=["S级对口", "央国企", "广东有岗"], pinned=True),
    S("longyuan", "龙源电力", "grid", "发电集团", "央企", "风力发电",
      alias="国能投龙源", apply_url="https://zhaopin.chnenergy.com.cn", official_site="https://www.clypg.com.cn",
      batch=["秋招", "春招"], status="未开启", positions=["电气运行", "风场检修", "海上风电"],
      cities=["北京", "全国风场（含广东）"], last_verified=VERIFIED_DATE,
      verify_note="随国家能源集团统一招聘平台报名（平台已核验），岗位内报龙源",
      deadline_note="预计2026年10-11月，随国能投统考",
      salary_text="转月约 8-12k×13",
      salary_structure="基本工资+绩效+场站补贴+年终，五险二金",
      desc="全球最大风电运营商（国家能源集团旗下）",
      ee_notes="风电场电气运行对口；风电场多在郊野，倒班+驻地补贴",
      tags=["S级对口", "央国企"]),
    S("cnnx", "中核汇能", "grid", "发电集团", "央企", "新能源",
      alias="中核新能源", apply_url="https://hr.cnnc.com.cn", official_site="https://www.cnnc.com.cn",
      batch=["秋招"], status="未开启", positions=["电气运行", "光伏/风电场站", "储能"],
      cities=["北京", "全国场站"], last_verified=VERIFIED_DATE,
      verify_note="随中核人才招聘网统一报名（平台已核验）",
      deadline_note="预计2026年9月起，随中核集团各单位分批",
      salary_text="转月约 9-13k",
      salary_structure="基本工资+绩效+场站补贴+年终，五险二金",
      desc="中核集团新能源平台，光伏/风电/储能扩张期",
      ee_notes="新能源场站电气对口；央企平台+新能源赛道组合",
      tags=["S级对口", "央国企"]),
]
