# -*- coding: utf-8 -*-
"""广东省内重点补充：电气对口的待遇好民企/中型企业（21 家）。

定位：用户在广东求职，除头部大厂外，省内中型装备/电子/电池民企招聘量大、
本科友好、性价比高。薪资均为公开渠道聚合口径，仅供参考。
"""
from .helpers import S

COMPANIES = [
    # ---------- 电池 ----------
    S("cosmx", "珠海冠宇电池", "newenergy", "电池", "民企", "消费/动力电池",
      alias="冠宇/COSMX", apply_url="https://campus.cosmxtech.com", official_site="https://www.cosmxtech.com",
      batch=["秋招", "春招", "实习"], status="未开启", positions=["电气设计", "设备工程师", "工艺", "测试"],
      cities=["珠海", "重庆", "浙江"], deadline_note="预计2026年9月开启",
      salary_text="本科转月约 10-13k×(13-14)",
      salary_structure="基本工资+绩效+年终，五险一金，上市公司",
      desc="全球消费电池 Pack 龙头（笔记本/手机电池），珠海基地",
      ee_notes="广东电池就业优选之一；设备/电气岗需求大，本科友好；珠海宜居",
      tags=["S级对口", "广东有岗", "本科友好"]),
    S("desay", "德赛电池", "newenergy", "电池", "国企", "消费电池/电源管理",
      alias="Desay", apply_url="https://campus.desay.com", official_site="https://www.desaybattery.com",
      batch=["秋招"], status="未开启", positions=["电气工程师", "设备", "测试", "工艺"],
      cities=["惠州"], deadline_note="预计2026年9月",
      salary_text="本科转月约 9-12k×13",
      salary_structure="基本工资+绩效+年终，五险一金，惠州国企背景上市",
      desc="消费电池+电源管理系统（惠州，苹果产业链）",
      ee_notes="惠州电池双子星之一（另一个是亿纬）；工厂电气/设备对口",
      tags=["S级对口", "广东有岗", "本科友好"]),

    # ---------- 锂电/产线装备 ----------
    S("lyric", "利元亨智能装备", "general", "高端制造", "民企", "锂电设备",
      alias="Lyric Robot", apply_url="https://campus.lyricrobot.com", official_site="https://www.lyricrobot.com",
      batch=["秋招", "春招"], status="未开启", positions=["电气工程师", "电控设计", "调试工程师", "PLC"],
      cities=["惠州", "上海", "宁德新疆基地"], deadline_note="预计2026年9月",
      salary_text="本科转月约 9-13k×13+项目奖",
      salary_structure="基本工资+绩效+项目奖金，五险一金，科创板上市",
      desc="锂电整线装备头部（惠州），宁德/比亚迪产线供应商",
      ee_notes="非标设备电气（电柜/伺服/PLC）大户，与先导智能同赛道；惠州基地，出差多但涨经验快",
      tags=["S级对口", "广东有岗", "本科友好"]),
    S("topstar", "拓斯达科技", "general", "高端制造", "民企", "工业机器人/自动化",
      alias="Topstar", apply_url="https://campus.topstar.com", official_site="https://www.topstar.com",
      batch=["秋招"], status="未开启", positions=["电气工程师", "电控设计", "调试", "机器人应用"],
      cities=["东莞"], deadline_note="预计2026年9月",
      salary_text="本科转月约 9-13k×13",
      salary_structure="基本工资+绩效+年终，五险一金，创业板上市",
      desc="机器人+注塑自动化整体方案商（东莞大岭山）",
      ee_notes="自动化设备电气设计/调试对口；东莞，制造业升级赛道",
      tags=["S级对口", "广东有岗", "本科友好"]),
    S("mino", "明珞装备", "general", "高端制造", "民企", "汽车产线装备",
      alias="MINO", apply_url="https://campus.minoinc.com", official_site="https://www.minoinc.com",
      batch=["秋招"], status="未开启", positions=["电气工程师", "PLC/电控", "调试工程师", "仿真"],
      cities=["广州"], deadline_note="预计2026年9月",
      salary_text="本科转月约 11-15k×(13-14)，广州装备圈待遇标杆",
      salary_structure="基本工资+项目绩效+年终，五险一金，客户为奔驰/宝马/宁德",
      desc="汽车白车身产线智能装备头部（广州黄埔），出海强",
      ee_notes="非标自动化电气天花板级中型民企：PLC/电控/调试全要电气；项目制出差，攒钱快",
      tags=["S级对口", "广东有岗", "本科友好"]),
    S("risong", "瑞松科技", "general", "高端制造", "民企", "机器人焊接集成",
      alias="Risong", apply_url="https://campus.gzrs.com", official_site="https://www.gzrs.com",
      batch=["秋招"], status="未开启", positions=["电气工程师", "PLC工程师", "调试"],
      cities=["广州"], deadline_note="预计2026年9月",
      salary_text="本科转月约 9-12k×13",
      salary_structure="基本工资+项目绩效+年终，五险一金，科创板上市",
      desc="机器人系统集成（焊接/装配线）科创板企业（广州）",
      ee_notes="产线电气设计/调试对口；广州，汽车装备链",
      tags=["S级对口", "广东有岗"]),
    S("gsk", "广州数控设备", "equipment", "工控/传动", "国企", "数控系统/机器人",
      alias="GSK", apply_url="https://campus.gsk.com", official_site="https://www.gsk.com",
      batch=["秋招"], status="未开启", positions=["电气工程师", "伺服研发", "调试", "应用工程师"],
      cities=["广州"], deadline_note="预计2026年9月",
      salary_text="本科转月约 8-11k×13",
      salary_structure="基本工资+绩效+年终，五险一金，广州国企背景",
      desc="国产数控系统龙头（广州），伺服/机器人全链",
      ee_notes="数控/伺服电气对口；国企稳定型，广州本地就业友好",
      tags=["S级对口", "广东有岗", "央国企", "本科友好"]),
    S("kdt", "弘亚数控", "general", "高端制造", "民企", "数控机床",
      alias="KDT", apply_url="https://campus.fskdt.com", official_site="https://www.fskdt.com",
      batch=["秋招"], status="未开启", positions=["电气工程师", "电控研发", "调试"],
      cities=["广州"], deadline_note="预计2026年9月",
      salary_text="本科转月约 9-12k×13",
      salary_structure="基本工资+绩效+年终，五险一金，上市民企",
      desc="家具数控装备全球头部（广州），盈利率高的隐形冠军",
      ee_notes="机床电控/电气设计对口；广州，闷声赚钱的中型装备厂",
      tags=["高度相关", "广东有岗"]),
    S("yizumi", "伊之密", "general", "高端制造", "民企", "注塑装备",
      alias="YIZUMI", apply_url="https://campus.yizumi.com", official_site="https://www.yizumi.com",
      batch=["秋招"], status="未开启", positions=["电气工程师", "电控设计", "调试"],
      cities=["佛山"], deadline_note="预计2026年9月",
      salary_text="本科转月约 9-12k×13",
      salary_structure="基本工资+绩效+年终，五险一金，上市民企",
      desc="注塑机全球第一梯队（佛山顺德），装备出海",
      ee_notes="注塑机电控/电气对口；顺德制造业集群，生活成本友好",
      tags=["高度相关", "广东有岗", "本科友好"]),
    S("envicool", "英维克科技", "general", "高端制造", "民企", "精密温控/液冷",
      apply_url="https://campus.envicool.com", official_site="https://www.envicool.com",
      batch=["秋招"], status="未开启", positions=["电气设计", "电控研发", "测试"],
      cities=["深圳", "苏州"], deadline_note="预计2026年9月",
      salary_text="本科转月约 10-13k×(13-14)",
      salary_structure="基本工资+绩效+年终，五险一金，上市公司",
      desc="数据中心/储能精密温控龙头（深圳），AI 液冷爆发受益者",
      ee_notes="AI 算力散热赛道；电气设计（配电/制冷电控）对口，成长性好",
      tags=["S级对口", "广东有岗"]),
    S("goaland", "高澜股份", "general", "高端制造", "民企", "液冷/水冷设备",
      alias="Goaland", apply_url="https://campus.goaland.com", official_site="https://www.goaland.com",
      batch=["秋招"], status="未开启", positions=["电气工程师", "电控设计", "测试"],
      cities=["广州", "东莞"], deadline_note="预计2026年9月",
      salary_text="本科转月约 9-12k×13",
      salary_structure="基本工资+绩效+年终，五险一金，上市公司",
      desc="电力电子/数据中心液冷设备（广州），前身电网系",
      ee_notes="电力电子装置水冷系统电气对口；广州",
      tags=["高度相关", "广东有岗"]),

    # ---------- 电源/工控 ----------
    S("leadshine", "雷赛智能", "equipment", "工控/传动", "民企", "运动控制",
      alias="Leadshine", apply_url="https://campus.leisai.com", official_site="https://www.leisai.com",
      batch=["秋招"], status="未开启", positions=["电气研发", "硬件", "应用工程师", "嵌入式"],
      cities=["深圳"], deadline_note="预计2026年9月",
      salary_text="本科转月约 10-14k×(13-14)",
      salary_structure="基本工资+绩效+年终，五险一金，上市公司",
      desc="步进/伺服运动控制龙头（深圳），机器人/半导体下游",
      ee_notes="运动控制+电气研发对口；比汇川小一档但同类赛道，深圳",
      tags=["S级对口", "广东有岗"]),
    S("hopewind", "禾望电气", "equipment", "电源设备", "民企", "风电变流/光伏逆变",
      alias="Hopewind", apply_url="https://campus.hopewind.com", official_site="https://www.hopewind.com",
      batch=["秋招"], status="进行中", positions=["电气研发", "电力电子硬件", "测试", "风电变流"],
      cities=["深圳", "苏州"], deadline_note="2027届校招进行中（核验确认），北森平台投递",
      salary_text="本科转月约 12-16k×(13-14)，电力电子好待遇",
      salary_structure="基本工资+绩效+年终，五险一金，上市公司",
      desc="风电变流器+光伏逆变器+工程传动（深圳）",
      ee_notes="电力电子方向对口度极高，与阳光/汇川同池竞争者；深圳，研发性价比高",
      tags=["S级对口", "广东有岗"]),
    S("jasic", "佳士科技", "equipment", "电源设备", "民企", "焊接电源",
      alias="JASIC", apply_url="https://campus.jasic.com", official_site="https://www.jasic.com.cn",
      batch=["秋招"], status="未开启", positions=["电气研发", "电力电子硬件", "测试"],
      cities=["深圳"], deadline_note="预计2026年9月",
      salary_text="本科转月约 9-12k×13",
      salary_structure="基本工资+绩效+年终，五险一金，上市公司",
      desc="逆变焊机出口龙头（深圳），逆变电源技术同源",
      ee_notes="电力电子/电源研发对口，逆变焊机=功率变换器，技术可迁移",
      tags=["高度相关", "广东有岗"]),
    S("infypower", "英飞源技术", "equipment", "电源设备", "民企", "充电模块",
      alias="Infypower", apply_url="https://campus.infypower.com", official_site="https://www.infypower.com",
      batch=["秋招"], status="未开启", positions=["电气研发", "电力电子硬件", "测试"],
      cities=["深圳"], deadline_note="预计2026年9月",
      salary_text="本科转月约 12-16k×(13-14)，充电模块龙头待遇好",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="充电桩功率模块全球份额第一（深圳）",
      ee_notes="电力电子黄金赛道小龙头；充电桩出海+液冷超充双风口",
      tags=["S级对口", "广东有岗"]),

    # ---------- 电子制造 ----------
    S("changying", "长盈精密", "general", "ICT硬件", "民企", "精密制造",
      apply_url="https://campus.everwin.com", official_site="https://www.everwin.com.cn",
      batch=["秋招"], status="未开启", positions=["电气工程师", "设备工程师", "自动化", "NPI"],
      cities=["深圳", "东莞", "宜宾", "常州"], deadline_note="预计2026年9月",
      salary_text="本科转月约 8-11k×13",
      salary_structure="基本工资+绩效+年终，五险一金，上市公司",
      desc="消费电子精密结构件+机器人零部件（深圳总部）",
      ee_notes="工厂电气/自动化设备岗量大；新能源结构件扩产带来需求",
      tags=["相关", "广东有岗", "本科友好"]),
    S("shengyi", "生益科技", "general", "ICT硬件", "国企", "覆铜板/电子材料",
      alias="SY Tech", apply_url="https://campus.syelectronics.com", official_site="https://www.syelectronics.com",
      batch=["秋招"], status="未开启", positions=["电气工程师", "设备工程师", "自动化", "仪表"],
      cities=["东莞", "陕西咸阳", "江苏常熟"], deadline_note="预计2026年9月",
      salary_text="本科转月约 10-13k×13，东莞制造业待遇标杆",
      salary_structure="基本工资+绩效+年终，五险一金+企业年金",
      desc="全球覆铜板第二（东莞松山湖），AI 服务器材料受益者",
      ee_notes="东莞待遇最好的制造业之一；工厂电气/设备/仪表对口，国企背景稳",
      tags=["高度相关", "广东有岗", "本科友好"]),
    S("sanhuan", "潮州三环", "general", "ICT硬件", "民企", "电子陶瓷/MLCC",
      alias="CCTC", apply_url="https://campus.cctc.cc", official_site="https://www.cctc.cc",
      batch=["秋招"], status="未开启", positions=["电气工程师", "设备工程师", "自动化"],
      cities=["潮州", "南充", "德阳"], deadline_note="预计2026年9月",
      salary_text="本科转月约 10-14k×13，潮州待遇天花板",
      salary_structure="基本工资+绩效+年终，五险一金，上市民企",
      desc="电子陶瓷/光纤陶瓷插芯/MLCC 全球龙头（潮州）",
      ee_notes="粤东制造业天花板待遇；设备电气/自动化对口，隐形冠军型 employers",
      tags=["高度相关", "广东有岗", "本科友好"]),
    S("foryou", "华阳集团", "general", "ICT硬件", "民企", "汽车电子",
      alias="FORYOU", apply_url="https://campus.foryou.com", official_site="https://www.foryou.com.cn",
      batch=["秋招"], status="未开启", positions=["电气工程师", "硬件", "测试", "设备"],
      cities=["惠州"], deadline_note="预计2026年9月",
      salary_text="本科转月约 8-11k×13",
      salary_structure="基本工资+绩效+年终，五险一金，上市公司",
      desc="车载影音/ HUD 汽车电子（惠州）",
      ee_notes="汽车电子制造电气岗；惠州生活成本低",
      tags=["相关", "广东有岗"]),

    # ---------- 央企/国企在粤 ----------
    S("crrc-gd", "中车广东轨道车辆", "general", "轨交", "央企", "城轨车辆制造",
      alias="中车江门基地", apply_url="https://campus.crrcgc.cc", official_site="https://www.crrcgc.cc",
      batch=["秋招"], status="未开启", positions=["电气调试", "车辆电气", "工艺"],
      cities=["江门新会"], deadline_note="预计2026年9-10月，随中车集团/子公司招聘",
      salary_text="转月约 8-11k，央企福利",
      salary_structure="基本工资+绩效+年终，五险二金",
      desc="中车在华南的城轨车辆造修基地（江门新会，珠三角城轨车辆供应方）",
      ee_notes="粤西/珠江西岸央企选项；车辆电气装配调试对口，本科友好",
      tags=["S级对口", "央国企", "广东有岗", "本科友好"]),
    S("hanlan", "瀚蓝环境", "grid", "地方能源", "国企", "固废发电/燃气",
      apply_url="https://campus.hanlan.com", official_site="https://www.hanlan.com",
      batch=["秋招"], status="未开启", positions=["电气运行", "电厂电气", "设备管理"],
      cities=["佛山", "全国垃圾焚烧电厂"], deadline_note="预计2026年9-10月",
      salary_text="转月约 8-11k，国企福利完善",
      salary_structure="基本工资+绩效+年终，五险一金，佛山南海国资上市",
      desc="固废焚烧发电+燃气运营（佛山），电厂电气岗稳定",
      ee_notes="垃圾焚烧电厂电气运行对口；佛山国企，稳定+离家近路线",
      tags=["S级对口", "央国企", "广东有岗", "本科友好"]),

    # ---------- 广海大人常去的省内雇主（就业网高频公告，爬虫自动同步动态） ----------
    S("gd-haid", "海大集团", "general", "高端制造", "民企", "农牧/智能制造",
      alias="广东海大", apply_url="https://www.haid.com.cn", official_site="https://www.haid.com.cn",
      batch=["秋招", "春招", "实习"], status="未开启", positions=["电气工程师", "设备工程师", "自动化", "智能制造"],
      cities=["广州", "全国生产基地（含粤西）"], last_verified=None,
      verify_note="官网入口待核验；校招公告在本校就业网高频发布，本站爬虫会自动同步到该企业动态",
      deadline_note="2027届校招公告已在广海大就业网发布（技术服务/技术员等岗），电气设备岗关注官网+就业网",
      salary_text="本科转月约 8-11k×13+驻地补贴",
      salary_structure="基本工资+绩效+年终，五险一金，农牧龙头待遇中上",
      desc="全国农牧龙头（广州番禺），饲料厂智能化改造大量要电气自动化",
      ee_notes="广海大招聘大户、地缘极强；饲料/养殖工厂的设备电气、自动化产线岗常年招，本科友好",
      tags=["相关", "广东有岗", "本科友好"]),
    S("deerma", "德尔玛科技", "general", "家电", "民企", "小家电",
      alias="Deerma", apply_url="https://www.deerma.com", official_site="https://www.deerma.com",
      batch=["秋招", "实习"], status="未开启", positions=["电气工程师", "设备工程师", "自动化"],
      cities=["佛山"], last_verified=None,
      verify_note="官网入口待核验；2027届实习生招聘公告已在本校就业网发布，爬虫自动同步",
      deadline_note="2027届实习生招聘已启动（就业网公告），秋招预计9月",
      salary_text="本科转月约 7-10k×13",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="小家电（飞利浦授权/水壶吸尘器）佛山中型民企",
      ee_notes="佛山小家电电气/设备岗，门槛友好，适合保底+积累",
      tags=["相关", "广东有岗", "本科友好"]),

    # ---------- AI 数据中心电力需求链（算力=耗电，备电/电源/配电/温控全线受益） ----------
    S("oulutong", "欧陆通科技", "equipment", "电源设备", "民企", "服务器电源",
      apply_url="https://campus.szport.com?以官网为准", official_site="https://www.szport.com",
      batch=["秋招"], status="未开启", positions=["电气研发", "电力电子硬件", "测试", "结构"],
      cities=["深圳", "河源"], deadline_note="预计2026年9月",
      salary_text="本科转月约 10-14k×(13-14)",
      salary_structure="基本工资+绩效+年终，五险一金，上市公司",
      desc="服务器电源龙头（深圳），AI 算力电源核心受益标的",
      ee_notes="AI 电力需求链核心：数据中心/服务器电源研发；电力电子对口，深圳",
      tags=["S级对口", "广东有岗"]),
    S("vertiv", "维谛技术（Vertiv）", "equipment", "外企电气", "外企", "数据中心电力/温控",
      alias="原艾默生网络能源", apply_url="https://www.vertiv.cn/zh-CN/careers/?以官网为准", official_site="https://www.vertiv.cn",
      batch=["秋招", "实习", "社招"], status="未开启", positions=["电气研发", "UPS/配电", "温控", "测试", "应用工程师"],
      cities=["深圳", "上海", "绵阳", "江门"], deadline_note="外企滚动招聘，秋招高峰9-10月",
      salary_text="转月约 11-16k×13，外企福利+数据中心景气加成",
      salary_structure="13薪+奖金，五险一金全额+补充医疗，外企 WLB",
      desc="数据中心电力与温控全球巨头（原艾默生网络能源，深圳大本营）",
      ee_notes="AI 算力基建核心外企：UPS/配电/精密空调全线；电气对口度极高，英语加分",
      tags=["S级对口", "外企", "广东有岗"]),
    S("csg-energy", "南网能源", "grid", "地方能源", "央企", "综合能源服务",
      alias="南方电网综合能源", apply_url="https://zhaopin.csg.cn", official_site="https://www.csg.cn",
      batch=["秋招"], status="未开启", positions=["电气工程师", "节能诊断", "分布式能源", "数据中心能效"],
      cities=["广州"], deadline_note="随南方电网统一招聘或单招（约9-10月）",
      salary_text="转月约 9-12k，央企福利",
      salary_structure="基本工资+绩效+年终，五险二金",
      desc="南网旗下综合能源服务平台（广州），数据中心节能改造主力",
      ee_notes="AI 耗电激增带火能效赛道；电气对口+央企平台，广州",
      tags=["S级对口", "央国企", "广东有岗"]),

    # ---------- 非标自动化补充 ----------
    S("boje", "博杰股份", "general", "高端制造", "民企", "自动化测试设备",
      apply_url="https://campus.bojiegufen.com?以官网为准", official_site="https://www.bojiegufen.com",
      batch=["秋招"], status="未开启", positions=["电气工程师", "电控设计", "调试", "机械"],
      cities=["珠海"], deadline_note="预计2026年9月",
      salary_text="本科转月约 9-13k×13",
      salary_structure="基本工资+绩效+项目奖，五险一金，上市公司",
      desc="消费电子自动化测试设备头部（珠海，苹果产业链）",
      ee_notes="非标自动化电控/调试对口；珠海，体量小于明珞但同类路径",
      tags=["S级对口", "非标自动化", "广东有岗", "本科友好"]),
    S("united-winners", "联赢激光", "general", "高端制造", "民企", "激光焊接装备",
      apply_url="https://campus.unitedwinners.com.cn?以官网为准", official_site="https://www.unitedwinners.com.cn",
      batch=["秋招"], status="未开启", positions=["电气工程师", "电控设计", "PLC", "调试"],
      cities=["深圳", "常州", "惠州"], deadline_note="预计2026年9月",
      salary_text="本科转月约 9-13k×13+项目奖",
      salary_structure="基本工资+绩效+项目奖金，五险一金，科创板上市",
      desc="激光焊接装备龙头（深圳），动力电池/汽车产线主力供应商",
      ee_notes="非标自动化电气（电柜/PLC/调试）大户；惠州基地就近可选",
      tags=["S级对口", "非标自动化", "广东有岗", "本科友好"]),
    S("jpt", "杰普特光电", "general", "高端制造", "民企", "激光智能装备",
      alias="JPT", apply_url="https://campus.jpt.com?以官网为准", official_site="https://www.jpt.com",
      batch=["秋招"], status="未开启", positions=["电气工程师", "电控", "调试", "硬件"],
      cities=["深圳"], deadline_note="预计2026年9月",
      salary_text="本科转月约 10-13k×13",
      salary_structure="基本工资+绩效+年终，五险一金，上市公司",
      desc="MOPA 脉冲激光器+激光智能装备（深圳），消费电子/新能源客户",
      ee_notes="激光装备非标电气对口；深圳，光电+自动化复合",
      tags=["非标自动化", "广东有岗"]),
    S("jiateng", "嘉腾机器人", "general", "高端制造", "民企", "AGV/自动化集成",
      apply_url="https://campus.jiateng.com?以官网为准", official_site="https://www.jiateng.com",
      batch=["秋招"], status="未开启", positions=["电气工程师", "PLC工程师", "调试", "嵌入式"],
      cities=["佛山"], deadline_note="预计2026年9月",
      salary_text="本科转月约 9-12k×13",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="AGV 移动机器人+自动化集成（佛山顺德，华为等大厂供应商）",
      ee_notes="移动机器人/集成产线电气对口；顺德，本地中型民企，门槛友好",
      tags=["S级对口", "非标自动化", "广东有岗", "本科友好"]),

    # ---------- 第二轮联网发掘（2026-08-30，AI 电力链 + 非标自动化 + 装备制造） ----------
    S("shenling", "申菱环境", "general", "高端制造", "民企", "数据中心温控/液冷",
      apply_url="https://www.shenling.com/careers/", official_site="https://www.shenling.com",
      batch=["秋招"], status="未开启", positions=["电气工程师", "电气图纸设计", "暖通电控", "测试"],
      cities=["佛山顺德"], last_verified="2026-08-30",
      verify_note="官网「加入申菱」在招电气工程师（佛山顺德），招聘平台同步 2026 电气工程师岗",
      deadline_note="预计2026年9月（AI 数据中心散热链核心供应商）",
      salary_text="校招本科约 6-8k×13（社招液冷/电气岗更高）",
      salary_structure="基本工资+绩效+年终，五险一金，创业板上市",
      desc="数据中心/工业温控与液冷设备商（佛山顺德），AI 散热链核心，与英维克同赛道",
      ee_notes="AI 数据中心温控链：电气图纸设计/BOM 选型对口；佛山顺德本地就业友好",
      tags=["S级对口", "广东有岗"]),
    S("increase", "英可瑞", "equipment", "电源设备", "民企", "充电/电力操作电源",
      alias="Increase", apply_url="https://www.szincrease.com", official_site="https://www.szincrease.com",
      batch=["秋招"], status="未开启", positions=["电气工程师", "硬件研发", "电源工程师"],
      cities=["深圳"], last_verified="2026-08-30",
      verify_note="校招简章明确招电气工程师（电源硬件方向，高校就业网确认）",
      deadline_note="预计2026年9月（充电桩模块+电力操作电源）",
      salary_text="校招电气工程师首年约 13-15w，社招硬件 30-50K·14薪",
      salary_structure="基本工资+绩效+年终，五险一金，创业板上市",
      desc="充电电源/电力操作电源/通信高频开关电源（深圳）",
      ee_notes="充电+直流电源赛道小而美；待遇在校招电源圈第一梯队；深圳",
      tags=["S级对口", "广东有岗"]),
    S("eaglerise", "伊戈尔电气", "equipment", "输配电设备", "民企", "变压器/电源磁性元件",
      alias="Eaglerise", apply_url="http://www.eaglerise.cn", official_site="http://www.eaglerise.cn",
      batch=["秋招"], status="未开启", positions=["变压器研发", "电气工程师", "工艺"],
      cities=["佛山"], last_verified="2026-08-30",
      verify_note="官网设社招职位列表；猎聘在招变压器研发工程师（电气方向）",
      deadline_note="预计2026年9月（数据中心/AI 电源链配套变压器）",
      salary_text="校招电气研发约 8-12K·13薪（硕士 15-20w/年），主任工程师 15-25K",
      salary_structure="基本工资+绩效+年终，五险一金，上市公司",
      desc="变压器+智能箱变+电源磁性元件（佛山），AI 电源链配套",
      ee_notes="变压器研发电气对口；佛山，AI 算力配电受益标的",
      tags=["S级对口", "广东有岗"]),
    S("yanmai", "燕麦科技", "general", "高端制造", "民企", "自动化测试设备",
      alias="Yanmade", apply_url="https://yanmade.com/joinus", official_site="https://yanmade.com",
      batch=["秋招"], status="未开启", positions=["电气工程师", "运控工程师", "电控", "机械"],
      cities=["深圳"], last_verified="2026-08-30",
      verify_note="校招工程技术人员要求电气类/电气工程及其自动化专业；猎聘在招运控（电控）工程师",
      deadline_note="预计2026年9月（FPC/消费电子自动化测试）",
      salary_text="运控工程师约 1.5-2万，高级 2-3万",
      salary_structure="基本工资+绩效+年终，五险一金，科创板上市",
      desc="FPC/消费电子自动化测试设备（深圳，科创板，苹果链）",
      ee_notes="非标自动化电控/运控对口；深圳，精密测试赛道",
      tags=["非标自动化", "广东有岗", "高度相关"]),
    S("manst", "曼恩斯特", "general", "高端制造", "民企", "锂电涂布非标设备",
      alias="Manst", apply_url="https://www.manst.com/job/", official_site="https://www.manst.com",
      batch=["秋招"], status="未开启", positions=["电气研发工程师", "电气一次工程师", "PLC调试"],
      cities=["深圳"], last_verified="2026-08-30",
      verify_note="BOSS直聘在招高级电气研发工程师（要求非标设备电气设计、AB/西门子PLC）",
      deadline_note="预计2026年9月（锂电狭缝涂布非标设备）",
      salary_text="电气研发约 1.5-2万，高级 18-20K",
      salary_structure="基本工资+绩效+年终，五险一金，创业板上市",
      desc="高精密狭缝涂布模头与锂电非标设备商（深圳）",
      ee_notes="锂电非标设备电气研发对口（AB/西门子 PLC）；深圳，细分冠军",
      tags=["S级对口", "非标自动化", "广东有岗"]),
    S("broad-ocean", "大洋电机", "equipment", "工控/传动", "民企", "电机/动力总成",
      alias="Broad-Ocean", apply_url="https://www.broad-ocean.com/broad-ocean-cn/post.html", official_site="https://www.broad-ocean.com",
      batch=["秋招"], status="未开启", positions=["电气工程师", "电机控制", "电力电子", "燃料电池电气"],
      cities=["中山"], last_verified="2026-08-30",
      verify_note="官网研发岗要求电气/电力电子/电机控制专业；2026届校招含电气工程师岗",
      deadline_note="预计2026年9月（微特电机+新能源动力总成+氢燃料电池）",
      salary_text="工艺/电气岗约 9-14K·13薪",
      salary_structure="基本工资+绩效+年终，五险一金，上市公司",
      desc="微特电机+新能源车动力总成+氢燃料电池龙头（中山，186 个在招岗位）",
      ee_notes="电机控制/电力电子黄金对口；中山本地大型上市民企，岗位供给大",
      tags=["S级对口", "广东有岗", "本科友好"]),
]
