# -*- coding: utf-8 -*-
"""新能源/车企/电池方向种子数据（28 家）。薪资均为公开渠道聚合口径，仅供参考。"""
from .helpers import S

COMPANIES = [
    # ---------- 电池 ----------
    S("catl", "宁德时代", "newenergy", "电池", "民企", "动力/储能电池",
      alias="CATL", apply_url="https://campus.catl.com", official_site="https://www.catl.com",
      batch=["秋招", "春招", "实习", "社招"], status="未开启", positions=["电气设计", "设备工程师", "BMS/电池测试", "工艺"],
      cities=["宁德", "深圳", "上海", "宜宾", "德国/匈牙利基地"], deadline_note="预计2026年9月初开启「凌云计划」校招，节奏快招满即止",
      salary_text="本科转月约 12-16k×(13-16)，年总包 20-30w",
      salary_structure="基本工资+绩效+年终（浮动大）+加班费，五险一金，高薪高强度",
      desc="全球动力+储能电池绝对龙头，电气需求量最大的民企之一",
      ee_notes="电气/自动化大量招设备与电气设计岗（厂务动力系统）；研发偏电化学/电子；加班强度大但攒钱快；base 宁德为主",
      tags=["S级对口", "本科友好"], pinned=True),
    S("byd", "比亚迪", "newenergy", "车企", "民企", "整车/电池/电子",
      apply_url="https://talent.byd.com", official_site="https://www.byd.com",
      batch=["秋招", "春招", "实习", "社招"], status="进行中", positions=["电气工程师", "硬件开发", "设备/工艺", "测试"],
      cities=["深圳", "西安", "长沙", "常州", "合肥", "郑州"], deadline_note="2027届秋招8月已开启（往年8月中旬起），滚动面试",
      salary_text="本科转月约 10-13k×12+利润奖（F类），C类略低",
      salary_structure="月薪×12+利润奖（约1-3个月），五险一金，免费班车/食堂，部分城市住房补贴",
      desc="整车+电池+电子全链路，电气招聘量全国第一梯队",
      ee_notes="电气岗位供给最大民企（设备/电气/硬件/测试全要）；本科院招量大门槛友好；地点多为基地城市；2027届窗口已开尽快投",
      tags=["S级对口", "本科友好"], pinned=True),
    S("eve", "亿纬锂能", "newenergy", "电池", "民企", "锂电池",
      alias="EVE", apply_url="https://campus.evebattery.com", official_site="https://www.evebattery.com",
      batch=["秋招", "春招", "实习"], status="未开启", positions=["电气设计", "设备工程师", "测试", "工艺"],
      cities=["惠州", "荆门", "成都", "马来西亚基地"], deadline_note="预计2026年9月开启",
      salary_text="本科转月约 10-13k×(13-14)",
      salary_structure="基本工资+绩效+年终，五险一金，上市公司",
      desc="锂电池头部（动力+储能+消费），惠州大本营",
      ee_notes="广东本地电池大户；设备/电气岗需求大，本科友好；储能赛道扩张",
      tags=["S级对口", "广东有岗", "本科友好"], pinned=True),
    S("sunwoda", "欣旺达", "newenergy", "电池", "民企", "消费/动力电池",
      apply_url="https://campus.sunwoda.com", official_site="https://www.sunwoda.com",
      batch=["秋招", "春招"], status="未开启", positions=["电气设计", "设备", "BMS测试"],
      cities=["深圳", "惠州", "南京"], deadline_note="预计2026年9月",
      salary_text="本科转月约 9-12k×(13-14)",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="消费电池Pack龙头+动力电池二线（深圳）",
      ee_notes="深圳电池大厂，电气/自动化对口；消费电子客户链稳定",
      tags=["S级对口", "广东有岗"]),
    S("guoxuan", "国轩高科", "newenergy", "电池", "民企", "动力电池",
      apply_url="https://campus.gotion.com", official_site="https://www.gotion.com",
      batch=["秋招"], status="未开启", positions=["电气设计", "设备", "工艺"],
      cities=["合肥", "南通", "越南基地"], deadline_note="预计2026年9月",
      salary_text="本科转月约 8-11k×(13-14)",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="大众控股动力电池企业（合肥）",
      ee_notes="合肥新能源集群一员；电气设备岗量大",
      tags=["S级对口"]),
    S("calb", "中创新航", "newenergy", "电池", "民企", "动力电池",
      alias="CALB", apply_url="https://campus.calb-tech.com", official_site="https://www.calb-tech.com",
      batch=["秋招"], status="未开启", positions=["电气设计", "设备", "工艺"],
      cities=["常州", "武汉", "成都", "葡萄牙基地"], deadline_note="预计2026年9月",
      salary_text="本科转月约 9-12k×(13-14)",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="动力电池第二梯队（常州/武汉基地扩张中）",
      ee_notes="扩产期设备/电气需求大；常州基地性价比可以",
      tags=["S级对口"]),

    # ---------- 光伏 ----------
    S("longi", "隆基绿能", "newenergy", "光伏", "民企", "光伏组件/硅片",
      apply_url="https://campus.longi.com", official_site="https://www.longi.com",
      batch=["秋招", "春招", "实习"], status="未开启", positions=["电气工程师", "设备", "工艺", "电站开发"],
      cities=["西安", "嘉兴", "银川", "马来西亚/越南"], deadline_note="预计2026年9月开启",
      salary_text="本科转月约 10-13k×13",
      salary_structure="基本工资+绩效+年终，五险一金，上市公司",
      desc="光伏组件全球龙头（西安总部）",
      ee_notes="工厂电气/设备岗量大；电站开发岗需要出差；光伏周期底部薪资涨幅放缓但体量仍大",
      tags=["S级对口"], pinned=True),
    S("jinko", "晶科能源", "newenergy", "光伏", "民企", "光伏组件",
      apply_url="https://campus.jinkosolar.com", official_site="https://www.jinkosolar.com",
      batch=["秋招"], status="未开启", positions=["电气工程师", "设备", "海外项目"],
      cities=["上饶", "滁州", "乐山", "东南亚"], deadline_note="预计2026年9月",
      salary_text="本科转月约 8-12k×13",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="组件出货全球前二（上饶总部）",
      ee_notes="N型产能扩张期，工厂电气需求稳定；海外基地机会多",
      tags=["S级对口"]),
    S("trinasolar", "天合光能", "newenergy", "光伏", "民企", "光伏组件/系统",
      alias="天合", apply_url="https://campus.trinasolar.com", official_site="https://www.trinasolar.com",
      batch=["秋招"], status="未开启", positions=["电气工程师", "储能系统", "设备"],
      cities=["常州", "义乌", "青海"], deadline_note="预计2026年9月",
      salary_text="本科转月约 8-12k×13",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="组件头部+光储系统（常州总部）",
      ee_notes="储能系统集成岗位电气对口度高",
      tags=["S级对口"]),
    S("ja-solar", "晶澳科技", "newenergy", "光伏", "民企", "光伏组件",
      apply_url="https://campus.jasolar.com", official_site="https://www.jasolar.com",
      batch=["秋招"], status="未开启", positions=["电气工程师", "设备"],
      cities=["北京", "邢台", "曲靖", "越南"], deadline_note="预计2026年9月",
      salary_text="本科转月约 8-11k×13",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="组件头部一体化企业",
      ee_notes="工厂电气/设备对口；京津冀+云南基地",
      tags=["高度相关"]),
    S("canadian-solar", "阿特斯", "newenergy", "光伏", "民企", "光伏/储能",
      alias="Canadian Solar", apply_url="https://campus.canadiansolar.com", official_site="https://www.canadiansolar.com",
      batch=["秋招"], status="未开启", positions=["电气设计", "储能系统", "设备"],
      cities=["苏州", "宿迁", "加拿大总部"], deadline_note="预计2026年9月",
      salary_text="本科转月约 9-12k×13",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="北美市场组件+储能系统集成大户（苏州）",
      ee_notes="储能PCS/系统集成电气对口；苏州基地",
      tags=["高度相关"]),
    S("tongwei", "通威股份", "newenergy", "光伏", "民企", "硅料/电池片/农牧",
      apply_url="https://campus.tongwei.com", official_site="https://www.tongwei.com",
      batch=["秋招"], status="未开启", positions=["电气工程师", "设备", "工艺"],
      cities=["成都", "乐山", "包头", "盐城"], deadline_note="预计2026年9月",
      salary_text="本科转月约 9-12k×13",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="硅料+电池片全球龙头（成都）",
      ee_notes="化工属性强，电气/仪表岗位规范；西南基地为主",
      tags=["高度相关"]),
    S("aiko", "爱旭股份", "newenergy", "光伏", "民企", "电池片/组件",
      apply_url="https://campus.aikosolar.com", official_site="https://www.aikosolar.com",
      batch=["秋招"], status="未开启", positions=["电气工程师", "设备", "工艺"],
      cities=["佛山", "珠海", "义乌", "济南"], deadline_note="预计2026年9月",
      salary_text="本科转月约 9-12k×13",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="ABC电池技术企业，佛山/珠海基地在广东",
      ee_notes="广东光伏制造代表；电气/设备岗对口，竞争小于头部组件厂",
      tags=["高度相关", "广东有岗"]),

    # ---------- 风电/逆变器/储能 ----------
    S("goldwind", "金风科技", "newenergy", "风电", "民企", "风电机组",
      apply_url="https://campus.goldwind.com", official_site="https://www.goldwind.com",
      batch=["秋招"], status="未开启", positions=["电气设计", "风机研发", "现场工程师", "调试"],
      cities=["北京", "乌鲁木齐", "盐城", "阳江", "澳大利亚"], deadline_note="预计2026年9月",
      salary_text="本科转月约 9-12k×13",
      salary_structure="基本工资+绩效+年终，五险一金，上市公司",
      desc="风机整机国内龙头",
      ee_notes="风机电气系统（变桨/主控/变流）研发与现场调试对口；现场岗出差多",
      tags=["S级对口"]),
    S("envision", "远景能源", "newenergy", "风电", "民企", "风机/电池/智能物联",
      alias="Envision", apply_url="https://campus.envisionenergy.com", official_site="https://www.envisionenergy.com",
      batch=["秋招", "实习"], status="未开启", positions=["电气研发", "变流器", "算法", "储能"],
      cities=["上海", "江阴", "鄂尔多斯"], deadline_note="预计2026年9月",
      salary_text="本科转月约 11-15k×(13-15)，新锐里薪资高",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="风机+储能+电池（远景动力）多线布局，智能化标签浓",
      ee_notes="变流器/电气研发技术含量高；节奏快偏互联网风格",
      tags=["S级对口"]),
    S("mingyang", "明阳智能", "newenergy", "风电", "民企", "海上风电",
      apply_url="https://campus.mywind.com", official_site="https://www.myse.com.cn",
      batch=["秋招"], status="未开启", positions=["电气设计", "海上风电", "现场工程师"],
      cities=["中山", "阳江", "揭阳", "汕尾", "欧洲基地"], deadline_note="预计2026年9月",
      salary_text="本科转月约 8-12k×13",
      salary_structure="基本工资+绩效+年终，五险一金，上市公司",
      desc="海上风电整机龙头，总部广东中山",
      ee_notes="广东风电就业代表；海上风电扩张期，电气/现场岗需求旺；中山总部地缘友好",
      tags=["S级对口", "广东有岗", "本科友好"], pinned=True),
    S("sungrow", "阳光电源", "newenergy", "逆变器/储能", "民企", "逆变器/储能",
      alias="Sungrow", apply_url="https://campus.sungrowpower.com", official_site="https://www.sungrowpower.com",
      batch=["秋招", "春招", "实习"], status="进行中", positions=["电气研发", "硬件", "储能系统", "测试"],
      cities=["合肥", "上海", "深圳"], deadline_note="2027届全球校招已启动（核验确认），投递走 Moka 系统",
      salary_text="本科转月约 11-14k×(14-15)，年总包 18-25w",
      salary_structure="基本工资+绩效+年终（效益好），五险一金，上市公司",
      desc="光伏逆变器全球第一+储能系统集成全球头部（合肥）",
      ee_notes="电力电子/电气研发黄金雇主之一；硬件研发以电子背景为主，电气可投储能系统/测试/电气设计；合肥生活成本低",
      tags=["S级对口"], pinned=True),
    S("huawei-de", "华为数字能源", "newenergy", "逆变器/储能", "民企", "光伏逆变器/储能/充电",
      alias="华为数能", apply_url="https://career.huawei.com", official_site="https://digitalpower.huawei.com",
      batch=["秋招", "实习"], status="未开启", positions=["硬件研发", "电气研发", "算法", "测试"],
      cities=["深圳", "东莞", "西安", "成都"], deadline_note="随华为统一校招（预计2026年9月），面试节奏快",
      salary_text="本科转月约 15-22k×(15-16)+TUP分红，年总包 25-40w",
      salary_structure="华为标准薪酬：月薪×15-16+TUP虚拟股分红+项目奖，五险一金高基数",
      desc="华为旗下光伏逆变器全球第一梯队+储能+数据中心电源",
      ee_notes="电气/电力电子硕博研发为主，硬件测试/供应链本科可投；薪酬外企化+高强度；走华为统一招聘平台选数字能源",
      tags=["S级对口", "本科友好"], pinned=True),
    S("goodwe", "固德威", "newenergy", "逆变器/储能", "民企", "户用逆变器",
      alias="GoodWe", apply_url="https://campus.goodwe.com", official_site="https://www.goodwe.com",
      batch=["秋招"], status="未开启", positions=["硬件研发", "电气", "嵌入式"],
      cities=["苏州"], deadline_note="预计2026年9月",
      salary_text="本科转月约 10-13k×13",
      salary_structure="基本工资+绩效+年终，五险一金，上市公司",
      desc="户用/工商业逆变器头部（苏州）",
      ee_notes="电力电子硬件对口；苏州安家友好",
      tags=["S级对口"]),
    S("ginlong", "锦浪科技", "newenergy", "逆变器/储能", "民企", "户用逆变器",
      alias="Ginlong Solis", apply_url="https://campus.ginlong.com", official_site="https://www.ginlong.com",
      batch=["秋招"], status="未开启", positions=["硬件研发", "电气", "测试"],
      cities=["宁波"], deadline_note="预计2026年9月",
      salary_text="本科转月约 10-13k×13",
      salary_structure="基本工资+绩效+年终，五险一金，上市公司",
      desc="户用逆变器全球头部（宁波）",
      ee_notes="电力电子研发对口；宁波宜居",
      tags=["S级对口"]),

    # ---------- 车企 ----------
    S("nio", "蔚来", "newenergy", "车企", "民企", "新能源整车",
      alias="NIO", apply_url="https://nio.jobs.feishu.cn", official_site="https://www.nio.com",
      batch=["秋招", "春招", "实习", "社招"], status="进行中", positions=["电气系统", "高压系统", "测试", "制造"],
      cities=["上海", "合肥", "南京"], deadline_note="2027届秋招8月已开启（「Spark」项目），滚动招聘",
      salary_text="本科转月约 12-16k×(13-15)，年总包 18-28w",
      salary_structure="基本工资+绩效+年终，五险一金全额，部分岗位期权",
      desc="高端纯电+换电网络，用户体验型车企",
      ee_notes="高压电气系统/电池系统岗位电气对口；合肥工厂制造电气岗量大；8月已开抓紧投",
      tags=["S级对口"], pinned=True),
    S("xpeng", "小鹏汽车", "newenergy", "车企", "民企", "新能源整车",
      alias="XPENG", apply_url="https://job.xiaopeng.com", official_site="https://www.xiaopeng.com",
      batch=["秋招", "春招", "实习", "社招"], status="进行中", positions=["电气系统", "高压", "整车测试", "制造"],
      cities=["广州", "肇庆", "武汉", "北京"], deadline_note="2027届秋招8月底已开启，广州总部",
      salary_text="本科转月约 12-16k×(13-15)，年总包 18-28w",
      salary_structure="基本工资+绩效+年终，五险一金全额+补充公积金",
      desc="智驾标签最浓的新势力，广州总部+肇庆工厂",
      ee_notes="广东车企优选；整车电气/高压系统对口；广州总部待遇在广东制造业里领先",
      tags=["S级对口", "广东有岗"], pinned=True),
    S("li-auto", "理想汽车", "newenergy", "车企", "民企", "新能源整车",
      alias="LI", apply_url="https://app.mokahr.com/campus-recruitment/lixiang", official_site="https://www.lixiang.com",
      batch=["秋招", "春招", "实习"], status="未开启", positions=["电气系统", "高压安全", "制造", "测试"],
      cities=["北京", "常州", "上海", "成都"], deadline_note="预计2026年9月开启",
      salary_text="本科转月约 12-16k×(14-15)，年总包 20-30w",
      salary_structure="基本工资+绩效+年终，五险一金全额",
      desc="增程/纯电双线盈利新势力",
      ee_notes="整车电气架构/高压系统对口；盈利车企薪酬稳定",
      tags=["S级对口"]),
    S("gac-aion", "广汽埃安", "newenergy", "车企", "国企", "新能源整车",
      alias="AION", apply_url="https://campus.gac.com", official_site="https://www.gacne.com.cn",
      batch=["秋招", "春招", "实习"], status="未开启", positions=["电气系统", "三电", "制造", "测试"],
      cities=["广州"], deadline_note="随广汽集团统一校招（预计2026年9月）",
      salary_text="本科转月约 10-14k×(13-15)，年总包 15-22w",
      salary_structure="广汽体系薪酬：基本+绩效+年终，五险一金全额+企业年金",
      desc="广汽新能源品牌，广州番禺智能生态工厂",
      ee_notes="广州国企背景车企；三电/整车电气对口；稳定性优于新势力",
      tags=["S级对口", "广东有岗"], pinned=True),
    S("geely", "吉利控股", "newenergy", "车企", "民企", "整车集团",
      apply_url="https://campus.zgh.com", official_site="https://zgh.com",
      batch=["秋招", "春招", "实习"], status="未开启", positions=["电气系统", "三电", "制造", "测试"],
      cities=["杭州", "宁波", "西安", "宝鸡"], deadline_note="预计2026年9月开启（吉利/极氪等品牌统一入口）",
      salary_text="本科转月约 10-14k×(13-14)",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="民营车企最大集团（吉利/极氪/银河多品牌）",
      ee_notes="极氪（宁波杭州湾）研发岗电气需求多；集团统一招聘分品牌",
      tags=["S级对口"]),
    S("changan", "长安汽车", "newenergy", "车企", "国企", "整车",
      apply_url="https://campus.changan.com.cn", official_site="https://www.changan.com.cn",
      batch=["秋招", "春招"], status="未开启", positions=["电气系统", "三电", "制造"],
      cities=["重庆", "合肥"], deadline_note="预计2026年9月",
      salary_text="本科转月约 9-13k×(13-14)",
      salary_structure="基本工资+绩效+年终，五险一金+企业年金",
      desc="兵装集团旗下央企控股车企，重庆大本营",
      ee_notes="央企控股+市场化薪酬；重庆生活成本友好",
      tags=["S级对口", "央国企"]),
    S("saic-gmw", "上汽通用五菱", "newenergy", "车企", "国企", "整车",
      alias="五菱", apply_url="https://campus.saicmotor.com", official_site="https://www.sgmw.com.cn",
      batch=["秋招"], status="未开启", positions=["电气工程师", "设备", "制造"],
      cities=["柳州", "青岛", "重庆"], deadline_note="预计2026年9-10月",
      salary_text="本科转月约 8-11k×(13-14)，柳州性价比极高",
      salary_structure="基本工资+绩效+年终，五险一金+企业年金",
      desc="国民车企（宏光MINI EV），柳州制造基地",
      ee_notes="柳州安家成本极低、车企稳定；工厂电气/设备岗量大，本科友好",
      tags=["高度相关", "本科友好"]),
    S("tesla", "特斯拉（中国）", "newenergy", "车企", "外企", "整车/储能",
      alias="Tesla", apply_url="https://www.tesla.cn/careers", official_site="https://www.tesla.cn",
      batch=["秋招", "实习", "社招"], status="未开启", positions=["电气工程师", "设备工程师", "储能Supercharger", "制造"],
      cities=["上海", "上海储能超级工厂"], deadline_note="校招滚动（9-11月高峰），上海超级工厂+储能厂",
      salary_text="本科转月约 12-16k×(13-15)+股票/季度奖，年总包 20-30w",
      salary_structure="基本工资+季度绩效奖+限制性股票，五险一金全额，17薪左右综合",
      desc="上海超级工厂+Megapack储能厂，制造业标杆",
      ee_notes="设备/电气工程师岗位偏好自动化+电气；英语好加分；制造强度大但体系一流；储能工厂扩招电气",
      tags=["S级对口", "外企"], pinned=True),
    S("svolt", "蜂巢能源", "newenergy", "电池", "民企", "动力电池",
      alias="SVOLT", apply_url="https://campus.reon.com.cn", official_site="https://www.svolt.cn",
      batch=["秋招"], status="未开启", positions=["电气设计", "设备工程师", "工艺"],
      cities=["常州", "盐城", "上饶", "遂宁"], deadline_note="预计2026年9月",
      salary_text="本科转月约 9-12k×(13-14)",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="长城系动力/储能电池企业，短刀电池标签",
      ee_notes="扩产期设备/电气岗需求稳定；常州基地为主",
      tags=["S级对口"]),
    S("hithium", "海辰储能", "newenergy", "电池", "民企", "储能电池",
      alias="HiTHIUM", apply_url="https://campus.hithium.com", official_site="https://www.hithium.com",
      batch=["秋招"], status="未开启", positions=["电气设计", "设备", "储能系统", "工艺"],
      cities=["厦门", "重庆"], deadline_note="预计2026年9月",
      salary_text="本科转月约 10-14k×(13-14)",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="储能电池头部新贵（厦门/重庆基地，出货全球前列）",
      ee_notes="储能赛道高成长；电气/设备岗量大；厦门宜居",
      tags=["S级对口"]),
    S("zeekr", "极氪智能科技", "newenergy", "车企", "民企", "高端纯电",
      alias="ZEEKR", apply_url="https://campus.zgh.com", official_site="https://www.zeekrlife.com",
      batch=["秋招", "春招", "实习"], status="未开启", positions=["电气系统", "高压", "三电", "测试"],
      cities=["宁波杭州湾", "杭州", "上海"], deadline_note="预计2026年9月，随吉利集团统一校招分品牌投递",
      salary_text="本科转月约 12-16k×(13-15)，年总包 18-26w",
      salary_structure="基本工资+绩效+年终，五险一金全额",
      desc="吉利旗下高端纯电品牌（浩瀚架构），研发在宁波杭州湾",
      ee_notes="整车电气/三电研发需求旺；吉利体系内薪资第一档",
      tags=["S级对口"]),
    S("leapmotor", "零跑汽车", "newenergy", "车企", "民企", "新能源整车",
      apply_url="https://campus.leapmotor.com", official_site="https://www.leapmotor.com",
      batch=["秋招", "春招", "实习"], status="未开启", positions=["电气系统", "三电", "制造", "测试"],
      cities=["杭州", "金华"], deadline_note="预计2026年9月开启",
      salary_text="本科转月约 11-15k×(13-14)",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="新势力销量前列（杭州总部，全域自研路线）",
      ee_notes="电气/三电岗位对标头部新势力且门槛稍友好；杭州安家",
      tags=["S级对口"]),
]
