# -*- coding: utf-8 -*-
"""机器人/具身智能方向种子数据（广东 + 成都）。

为什么电气专业要关注具身智能：人形/协作/移动机器人的核心硬件链——
关节电机驱动、电源架构、电池管理、传感器电气、线束/FPC、整机电气测试——
几乎全是电气工程的主场。行业 2024-2026 处于爆发期，岗位供给快速增长，
初创公司多、门槛看项目经历（电赛/RoboMaster/机器人比赛经历很加分）。
薪资均为公开渠道聚合口径，仅供参考。
"""
from .helpers import S

COMPANIES = [
    S("ubtech", "优必选科技", "general", "机器人/具身智能", "民企", "人形机器人",
      alias="UBTECH", apply_url="https://www.ubtrobot.com/cn/about/recruit?以官网为准", official_site="https://www.ubtrobot.com",
      batch=["秋招", "实习", "社招"], status="未开启", positions=["电气工程师", "硬件工程师", "电机驱动", "电池管理", "测试"],
      cities=["深圳", "北京"], deadline_note="人形机器人 Walker 系列进厂实训中，产线交付扩张期岗位多",
      salary_text="本科约 12-18k×(13-15)，硬件/电气岗需求持续",
      salary_structure="基本工资+绩效+年终，五险一金，港股上市公司（09880）",
      desc="人形机器人第一股（深圳），Walker S 进车企工厂实训，硬件团队扩张",
      ee_notes="人形机器人电气天花板雇主：关节驱动/电源架构/线束整机全要电气；有机器人比赛或电赛经历大幅加分",
      tags=["S级对口", "广东有岗"]),
    S("dobot", "越疆科技", "general", "机器人/具身智能", "民企", "协作机械臂/具身智能",
      alias="Dobot", apply_url="https://www.dobot.cn?以官网为准", official_site="https://www.dobot.cn",
      batch=["秋招", "实习"], status="未开启", positions=["电气工程师", "硬件研发", "电机控制", "测试"],
      cities=["深圳"], deadline_note="港股 02432，协作机械臂出货量全球前列，具身智能产品线扩张",
      salary_text="本科约 12-16k×(13-15)",
      salary_structure="基本工资+绩效+年终，五险一金，上市公司",
      desc="协作机械臂全球头部（深圳），自带具身智能路线（机械臂+大模型）",
      ee_notes="机械臂电气（驱动器/控制柜/传感）对口；比人形公司稳健，出货真实",
      tags=["S级对口", "广东有岗"]),
    S("limx", "逐际动力", "general", "机器人/具身智能", "民企", "人形/四足机器人",
      alias="LimX Dynamics", apply_url="https://www.limxdynamics.com?以官网为准", official_site="https://www.limxdynamics.com",
      batch=["秋招", "实习"], status="未开启", positions=["电气工程师", "硬件工程师", "电机驱动", "电源"],
      cities=["深圳"], deadline_note="人形 W1/四轮足 W1 定位物流与工业场景，融资充裕",
      salary_text="本科约 13-18k×(13-15)，初创给期权",
      salary_structure="基本工资+绩效+期权激励，五险一金",
      desc="深圳人形/四足机器人头部创企（清华系团队），技术路线激进",
      ee_notes="初创型人形公司：电气一人多岗（电源+驱动+线束全包），成长极快但节奏狠",
      tags=["S级对口", "广东有岗"]),
    S("lejurobot", "乐聚机器人", "general", "机器人/具身智能", "民企", "人形机器人",
      alias="Leju", apply_url="https://www.lejurobot.com?以官网为准", official_site="https://www.lejurobot.com",
      batch=["秋招"], status="未开启", positions=["电气工程师", "硬件工程师", "结构电气"],
      cities=["深圳", "苏州"], deadline_note="「夸父」人形已进多个场景交付，规模扩张",
      salary_text="本科约 10-15k×13",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="人形机器人「夸父」制造商（深圳），教育/工业场景落地",
      ee_notes="人形整机电气岗；初创体量，适合想全栈接触人形硬件的同学",
      tags=["S级对口", "广东有岗"]),
    S("engineai", "众擎机器人", "general", "机器人/具身智能", "民企", "人形机器人",
      alias="EngineAI", apply_url="https://www.engineai.com.cn?以官网为准", official_site="https://www.engineai.com.cn",
      batch=["秋招", "实习"], status="未开启", positions=["电气工程师", "硬件工程师", "电机驱动"],
      cities=["深圳"], deadline_note="人形 SE01/PM01 出货中，团队年轻节奏快",
      salary_text="本科约 12-16k×(13-15)",
      salary_structure="基本工资+绩效+期权，五险一金",
      desc="深圳人形机器人新锐（SE01 全尺寸人形，动作控制出圈）",
      ee_notes="人形电气/驱动岗；团队小成长快，适合拼劲足的同学",
      tags=["S级对口", "广东有岗"]),
    S("astibot", "星尘智能", "general", "机器人/具身智能", "民企", "智能机械臂",
      alias="Astibot", apply_url="https://www.astibot.com?以官网为准", official_site="https://www.astibot.com",
      batch=["秋招", "实习"], status="未开启", positions=["电气工程师", "硬件工程师", "电机驱动", "传感"],
      cities=["深圳"], deadline_note="Astibot S1（双臂轮式）遥操作操作数据路线，融资顺利",
      salary_text="本科约 12-16k×(13-15)",
      salary_structure="基本工资+绩效+期权，五险一金",
      desc="具身智能双臂机器人 S1（深圳），数据采集型技术路线代表",
      ee_notes="整机电气/传感/驱动岗；小团队电气话语权大",
      tags=["S级对口", "广东有岗"]),
    S("youibot", "优艾智合", "general", "机器人/具身智能", "民企", "移动机器人",
      alias="Youibot", apply_url="https://www.youibot.com?以官网为准", official_site="https://www.youibot.com",
      batch=["秋招"], status="未开启", positions=["电气工程师", "硬件工程师", "电源", "测试"],
      cities=["深圳"], deadline_note="工业/巡检移动机器人落地多（半导体/电厂）",
      salary_text="本科约 10-14k×(13-14)",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="工业移动机器人+巡检机器人（深圳，软银/软通等投资）",
      ee_notes="移动机器人电气（电源/驱动/充电系统）对口；电厂巡检场景与电气专业天然相关",
      tags=["S级对口", "广东有岗"]),
    S("agilex", "松灵机器人", "general", "机器人/具身智能", "民企", "科研机器人底盘",
      alias="AgileX", apply_url="https://www.agilex.ai?以官网为准", official_site="https://www.agilex.ai",
      batch=["秋招"], status="未开启", positions=["电气工程师", "硬件研发", "电机驱动", "测试"],
      cities=["深圳"], deadline_note="全球高校科研底盘市占率高，具身智能科研生态核心供应商",
      salary_text="本科约 10-14k×13",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="科研机器人底盘/具身智能硬件平台（深圳，高校实验室标配）",
      ee_notes="底盘电气（驱动/电源/传感接口）对口；产品面向全球高校，出海氛围浓",
      tags=["S级对口", "广东有岗"]),
    S("xag", "极飞科技", "general", "机器人/具身智能", "民企", "农业无人机/机器人",
      alias="XAG", apply_url="https://www.xa.com/join?以官网为准", official_site="https://www.xa.com",
      batch=["秋招", "实习"], status="未开启", positions=["电气工程师", "硬件研发", "电源", "电机", "测试"],
      cities=["广州"], deadline_note="农业无人机+农机自动化头部，科创板已受理",
      salary_text="本科约 11-15k×(13-15)",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="农业科技龙头（广州），植保无人机+农机自动驾驶+遥感机器人",
      ee_notes="无人机/农机电气（动力电源/电机/传感）对口；广州，硬件团队规模大",
      tags=["S级对口", "广东有岗"]),
    S("crprobot", "卡诺普", "general", "机器人/具身智能", "民企", "机器人控制器/焊接机器人",
      alias="CRP Robot", apply_url="https://www.crprobot.com?以官网为准", official_site="https://www.crprobot.com",
      batch=["秋招"], status="未开启", positions=["电气工程师", "硬件工程师", "伺服驱动", "测试"],
      cities=["成都"], deadline_note="成都机器人产业链链主企业，控制器国产替代主力",
      salary_text="本科约 8-12k×13，成都生活成本友好",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="成都机器人龙头：机器人控制器市占国产第一，整线焊接机器人放量",
      ee_notes="成都具身/机器人圈首选；控制器+伺服驱动电气对口；成都安家性价比极高",
      tags=["S级对口", "本科友好"]),

    # ---------- 第二轮联网核验补充（2026-08-30，具身智能产业链） ----------
    S("cdhmc", "成都人形机器人创新中心", "general", "机器人/具身智能", "事业单位", "人形机器人/具身大模型",
      apply_url="https://www.zhaopin.com/companydetail/jobs-CZL1482801620/", official_site="",
      batch=["秋招", "社招"], status="进行中", positions=["嵌入式硬件工程师", "硬件系统集成", "电机驱动", "电池管理"],
      cities=["成都"], last_verified="2026-08-30",
      verify_note="无独立官网，招聘走智联企业页（已核验）；嵌入式硬件岗含永磁同步电机驱动电路、PCB Layout",
      deadline_note="常年招聘（技术岗部分 2-3.5万·13薪）",
      salary_text="技术岗约 2-3.5万·13薪",
      salary_structure="基本工资+绩效+年终，事业单位背景+市场化绩效",
      desc="中西部首个人形机器人创新中心（成都），贡嘎/镋钯/锦宝人形 + R-DDPRM 具身大模型",
      ee_notes="成都具身智能旗舰机构：电机驱动电路/电池管理/系统集成明确要电气专业；事业单位稳定性+行业风口",
      tags=["S级对口", "本科友好"]),
    S("buffalo", "布法罗机器人", "general", "机器人/具身智能", "民企", "外骨骼康复机器人",
      apply_url="https://m.liepin.com/company/9662832/", official_site="https://www.buffalo-robot.com",
      batch=["秋招", "社招"], status="未开启", positions=["硬件工程师", "电气工程师"],
      cities=["成都"], last_verified="2026-08-30",
      verify_note="BOSS直聘在招硬件工程师（硬件总体设计方案，本科3-5年）；官网 buffalo-robot.com",
      deadline_note="康复机器人已获医疗器械注册证，研发扩张",
      salary_text="硬件工程师面议（成都）",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="下肢外骨骼康复机器人（成都，电子科大程洪团队创办）",
      ee_notes="医疗机器人硬件总体设计对口；电子科大背景技术团队",
      tags=["S级对口"]),
    S("eventec", "越凡创新", "general", "机器人/具身智能", "民企", "商用配送机器人",
      alias="Eventec", apply_url="https://www.zhaopin.com/companydetail/CZ598289180.htm", official_site="http://www.eventec.cn",
      batch=["秋招", "社招"], status="未开启", positions=["电气工程师", "硬件工程师", "机械结构"],
      cities=["成都"], last_verified="2026-08-30",
      verify_note="智联企业页已核验；双选会信息提及在招研发电气工程师、硬件工程师",
      deadline_note="商用配送机器人「享递」可自主乘梯，全链路自研",
      salary_text="面议（成都）",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="商用移动/配送机器人（成都），全链路自研",
      ee_notes="成都机器人圈补充选项；电气/硬件研发岗",
      tags=["S级对口"]),
    S("pudu", "普渡机器人", "general", "机器人/具身智能", "民企", "商用配送机器人/具身智能",
      alias="Pudu Robotics", apply_url="https://pudutech.zhiye.com/", official_site="https://www.pudurobot.com",
      batch=["秋招", "实习", "社招"], status="进行中", positions=["硬件工程师", "电机控制工程师", "FPGA", "下位机硬件"],
      cities=["深圳", "成都"], last_verified="2026-08-30",
      verify_note="北森官方招聘平台已核验；校招硬件类 10-20K/月，社招硬件（电机方向）20-45K·14薪",
      deadline_note="全球商用配送机器人出货量领先，深圳+成都双研发基地",
      salary_text="校招硬件类 10-20K/月，社招电机方向 20-45K·14薪",
      salary_structure="基本工资+绩效+年终，五险一金",
      desc="商用配送机器人全球出货第一梯队（深圳/成都双基地），向具身智能延伸",
      ee_notes="出货真实的机器人公司：电机控制/下位机硬件电气对口；深圳成都双选，薪档在行业内偏上",
      tags=["S级对口", "广东有岗", "本科友好"]),
]
