# -*- coding: utf-8 -*-
"""链接核验结果（2026-08-29 由联网核验代理逐家确认）。

build_seed 会把这里的 apply_url / official_site / last_verified / verify_note
覆盖到同 id 的种子记录上，并追加 verified 来源。
confidence 由 note 体现：high=直接打开确认；medium=多方信源或按届更新域名。
"""

VERIFIED_DATE = "2026-08-29"

VERIFIED = {
    "sgcc": {"apply_url": "https://zhaopin.sgcc.com.cn", "last_verified": VERIFIED_DATE,
             "verify_note": "国网人资招聘平台，官方信源确认；站点有 WAF 拦自动化访问，浏览器人工可达"},
    "csg": {"apply_url": "https://zhaopin.csg.cn", "last_verified": VERIFIED_DATE,
            "verify_note": "员工招聘系统为南网校招唯一官方投递渠道（页面 JS 渲染）"},
    "chnenergy": {"apply_url": "https://zhaopin.chnenergy.com.cn", "last_verified": VERIFIED_DATE,
                  "verify_note": "官方招聘网站确认；抓取时 503 疑为临时防爬"},
    "spic": {"apply_url": "https://zhaopin.spic.com.cn", "last_verified": None,
             "verify_note": "招聘平台两次 503 未直接验到；2026届网申走国聘专区（域名按届更新如 spic2026.iguopin.com），2027届以官网公告为准"},
    "chng": {"apply_url": "https://zhaopin.chng.com.cn", "last_verified": VERIFIED_DATE,
             "verify_note": "已更正：campus.chng.com.cn 不存在，zhaopin.chng.com.cn 为校招唯一官方报名主站，确认可达"},
    "datang": {"apply_url": "https://zhaopin.china-cdt.com", "official_site": "https://www.china-cdt.com",
               "last_verified": VERIFIED_DATE,
               "verify_note": "多方信源确认为集团官方招聘平台；直连超时未打开；官网为 china-cdt.com"},
    "huadian": {"apply_url": "https://rencaishichang.chd.com.cn", "last_verified": VERIFIED_DATE,
                "verify_note": "华电人才市场平台确认可达（JS渲染），官方公告仅接受该平台线上报名"},
    "ctg": {"apply_url": "https://chrcmp.chinahr.com/pages/sanxia/", "last_verified": VERIFIED_DATE,
            "verify_note": "官方投递通道为中华英才网托管专区，页面可达"},
    "cgn": {"apply_url": "https://cgn.hotjob.cn", "last_verified": VERIFIED_DATE,
            "verify_note": "已更正：campus.cgnpc.com.cn 不存在；cgn.hotjob.cn 为中广核唯一官方校招平台，确认可达"},
    "cnnc": {"apply_url": "https://hr.cnnc.com.cn", "last_verified": VERIFIED_DATE,
             "verify_note": "确认可达（302 跳转官网招聘频道）"},
    "powerchina": {"apply_url": "https://zhaopin.powerchina.cn", "last_verified": VERIFIED_DATE,
                   "verify_note": "已更正：campus.powerchina.cn 不存在；zhaopin.powerchina.cn 为官方招聘平台，确认可达"},
    "ceec": {"apply_url": "https://ceec.iguopin.com", "last_verified": VERIFIED_DATE,
             "verify_note": "官方公告称其为能建全球校招唯一官方网申渠道（国聘专区），确认可达"},
    "gzcb": {"apply_url": "https://ceec.iguopin.com", "last_verified": VERIFIED_DATE,
             "verify_note": "随能建在国聘专区统一校招，入口已确认"},
    "gedi": {"apply_url": "https://ceec.iguopin.com", "last_verified": VERIFIED_DATE,
             "verify_note": "能建国聘专区内报广东院（GEDI），专区入口已确认"},
    "csedi": {"apply_url": "https://ceec.iguopin.com", "last_verified": VERIFIED_DATE,
              "verify_note": "能建国聘专区内报中南院，专区入口已确认"},
    "npdi": {"apply_url": "https://ceec.iguopin.com", "last_verified": VERIFIED_DATE,
             "verify_note": "能建国聘专区内报华北院，专区入口已确认"},
    "swedi": {"apply_url": "https://ceec.iguopin.com", "last_verified": VERIFIED_DATE,
              "verify_note": "能建国聘专区内报西南院，专区入口已确认"},
    "ecidi": {"apply_url": "https://zhaopin.powerchina.cn", "last_verified": VERIFIED_DATE,
              "verify_note": "电建招聘平台内报华东院，平台入口已确认"},
    "nwindi": {"apply_url": "https://zhaopin.powerchina.cn", "last_verified": VERIFIED_DATE,
               "verify_note": "电建招聘平台内报西北院，平台入口已确认"},
    "dongfang": {"apply_url": "https://dec2026.iguopin.com/job", "last_verified": VERIFIED_DATE,
                 "verify_note": "官方招聘为国聘专区，域名按届更新（当前为2026届专区），2027届以官网/公众号新链接为准"},
    "shanghai-electric": {"apply_url": "https://sec.hotjob.cn", "last_verified": VERIFIED_DATE,
                          "verify_note": "上海电气微招聘官网确认可达，校招社招统一网申入口"},
    "gpg": {"apply_url": "https://geg2026.zhaopin.com", "official_site": "https://www.geg.com.cn",
            "last_verified": VERIFIED_DATE,
            "verify_note": "2026届校招官网（智联托管，按届更新）；官网域名 geg.com.cn，gdyd.com 为旧域名"},
    "sec": {"apply_url": "https://campus.51job.com/szny2026", "last_verified": VERIFIED_DATE,
            "verify_note": "2026届校招官方投递为前程无忧专区（按届更新）；官网 sec.com.cn 确认可达"},
    "byd": {"apply_url": "https://job.byd.com", "last_verified": VERIFIED_DATE,
            "verify_note": "已更正：talent.byd.com 不存在；job.byd.com 为比亚迪人力资源服务平台，确认可达"},
    "catl": {"apply_url": "https://talent.catl.com", "last_verified": VERIFIED_DATE,
             "verify_note": "多所高校就业网确认为唯一官方网申入口；站点为 SPA 多层跳转，域名有效"},
    "huawei": {"apply_url": "https://career.huawei.com", "last_verified": VERIFIED_DATE,
               "verify_note": "确认可达，2027届校招专页已上线启动"},
    "huawei-de": {"apply_url": "https://career.huawei.com", "last_verified": VERIFIED_DATE,
                  "verify_note": "随华为统一校招平台（选数字能源/智能电动方向），平台已确认"},
    "nio": {"apply_url": "https://campus.nio.com", "official_site": "https://www.nio.cn",
            "last_verified": VERIFIED_DATE,
            "verify_note": "蔚来校招官网确认可达，2027届秋季校招进行中"},
    "xpeng": {"apply_url": "https://xiaopeng.jobs.feishu.cn/campus/", "last_verified": VERIFIED_DATE,
              "verify_note": "小鹏校招官网（飞书招聘）确认可达，2027届校招岗位可投递"},
    "li-auto": {"apply_url": "https://www.lixiang.com/employ/campus.html", "last_verified": VERIFIED_DATE,
                "verify_note": "官网校园招聘页确认可达，「立即投递」跳转投递入口"},
    "midea": {"apply_url": "https://careers.midea.com", "last_verified": VERIFIED_DATE,
              "verify_note": "美的校招官网确认可达"},
    "gree": {"apply_url": "https://zhaopin.greeyun.com", "last_verified": VERIFIED_DATE,
             "verify_note": "格力招聘系统确认可达，含校招/社招栏目"},
    "inovance": {"apply_url": "https://recruit.inovance.com", "last_verified": VERIFIED_DATE,
                 "verify_note": "汇川招聘官网确认可达；校招职位页 inovance.zhiye.com/campus/jobs"},
    "sungrow": {"apply_url": "https://jobs.sungrowpower.com", "last_verified": VERIFIED_DATE,
                "verify_note": "阳光电源招聘官网确认可达，2027届全球校招已启动（投递走 Moka）"},
    "tbea": {"apply_url": "https://tbea.hotjob.cn", "last_verified": VERIFIED_DATE,
             "verify_note": "特变电工微招聘确认可达（302 跳官方门户为正常），2026/2027 校招可申请"},
    "nari": {"apply_url": "https://job.sgepri.sgcc.com.cn", "last_verified": VERIFIED_DATE,
             "verify_note": "南瑞集团官方招聘网站（校招页已确认，WAF 拦自动化人工可达）；注意国网统招需另在国网平台报名"},

    # ---------- 广东省民企补充（2026-08-29 第二轮核验） ----------
    "cosmx": {"apply_url": "https://cosmx.zhiye.com/campus", "official_site": "http://www.cosmx.com",
              "last_verified": VERIFIED_DATE,
              "verify_note": "北森官方校招网申（页面标题确认为珠海冠宇电池股份有限公司）"},
    "desay": {"apply_url": "http://campus.51job.com/desay/gsjs.html", "official_site": "https://www.desaybattery.com",
              "last_verified": VERIFIED_DATE,
              "verify_note": "官网无直投链接，51job 校招专页为官方合作网申渠道"},
    "lyric": {"apply_url": "https://liyuanheng.zhiye.com/campus/jobs", "official_site": "https://www.lyric-robot.com",
              "last_verified": VERIFIED_DATE,
              "verify_note": "官网招聘入口指向北森 liyuanheng.zhiye.com，已核实"},
    "topstar": {"apply_url": "https://www.topstarltd.com/lang-cn/recruitinglist/006002003.html",
                "official_site": "https://www.topstarltd.com", "last_verified": VERIFIED_DATE,
                "verify_note": "官网人才招聘板块（校招/社招列表）已核实"},
    "mino": {"apply_url": "https://minotech.zhiye.com/Campus", "official_site": "https://www.minotech.cn",
             "last_verified": VERIFIED_DATE,
             "verify_note": "官网招聘入口指向北森 minotech.zhiye.com，页面标题确认为广州明珞"},
    "risong": {"apply_url": "http://www.risongtc.com", "official_site": "http://www.risongtc.com",
               "last_verified": VERIFIED_DATE,
               "verify_note": "官网证书异常未能直验（低置信）；招聘走官网人才栏目与 hr@risongtc.com 邮箱"},
    "gsk": {"apply_url": "https://www.gsk.com.cn/xyzp/index_1018.aspx", "official_site": "https://www.gsk.com.cn",
            "last_verified": VERIFIED_DATE,
            "verify_note": "官网「加入我们-校园招聘」栏目已核实（外链前程无忧 campus.51job.com/gsk）"},
    "kdt": {"apply_url": "https://www.kdtmac.com/joinus/1983059370596147200.html", "official_site": "https://www.kdtmac.com",
            "last_verified": VERIFIED_DATE,
            "verify_note": "官网「加入弘亚」校园招聘页已核实，支持在线投递"},
    "yizumi": {"apply_url": "https://yizumi.zhiye.com/", "official_site": "https://www.yizumi.com",
               "last_verified": VERIFIED_DATE,
               "verify_note": "北森官方招聘平台已核实"},
    "leadshine": {"apply_url": "https://www.leisai.com/recruitment/index.html", "official_site": "https://www.leisai.com",
                  "last_verified": VERIFIED_DATE,
                  "verify_note": "官网招聘板块已核实（岗位列表托管于 Moka）"},
    "hopewind": {"apply_url": "https://hopewind.zhiye.com/home", "official_site": "https://www.hopewind.com",
                 "last_verified": VERIFIED_DATE,
                 "verify_note": "北森官方招聘主页已核实；2027届校招进行中"},
    "envicool": {"apply_url": "https://envicool.zhiye.com/jobs", "official_site": "https://www.envicool.com",
                 "last_verified": VERIFIED_DATE,
                 "verify_note": "北森官方投递系统已核实"},
    "jasic": {"apply_url": "https://jasic.zhiye.com/", "official_site": "https://www.jasic.com.cn",
              "last_verified": VERIFIED_DATE,
              "verify_note": "北森「佳士科技招聘门户」已核实"},
    "infypower": {"apply_url": "https://www.infypower.cn/career", "official_site": "https://www.infypower.cn",
                  "last_verified": VERIFIED_DATE,
                  "verify_note": "官网人才招聘页已核实（岗位在线申请）"},
    "changying": {"apply_url": "https://www.ewpt.com/Job.html", "official_site": "https://www.ewpt.com",
                  "last_verified": VERIFIED_DATE,
                  "verify_note": "官网「加入长盈」招聘总入口已核实（含校园招聘子页）"},
    "shengyi": {"apply_url": "https://www.syst.com.cn/cn/zwztc/index_77.aspx", "official_site": "https://www.syst.com.cn",
                "last_verified": VERIFIED_DATE,
                "verify_note": "官网人才招聘-校园招聘「职位直通车」已核实（含校招行程）"},
    "sanhuan": {"apply_url": "https://hr.cctc.cc/", "official_site": "https://www.cctc.cc",
                "last_verified": VERIFIED_DATE,
                "verify_note": "官方招聘站 hr.cctc.cc 已核实（含校招通道）"},
    "foryou": {"apply_url": "http://www.foryougroup.com/dz_zhaopinxz.html", "official_site": "http://www.foryougroup.com",
               "last_verified": VERIFIED_DATE,
               "verify_note": "官网校园招聘页已核实"},
    "crrc-gd": {"apply_url": "https://crrc.hotjob.cn/", "official_site": "https://www.crrcgc.cc",
                "last_verified": VERIFIED_DATE,
                "verify_note": "中车集团官方招聘云平台已核实（含中车广东校招公告）"},
    "hanlan": {"apply_url": "https://www.zhaopin.com/companydetail/CZ478958610.htm", "official_site": "https://www.grandblue.cn",
               "last_verified": VERIFIED_DATE,
               "verify_note": "官网 grandblue.cn 已核实但无招聘栏目；招聘以智联企业账号（40+岗位直招）及公众号「人在瀚蓝」为主"},
    "goaland": {"apply_url": "https://m.zhipin.com/companys/829c8783182553201HV83dy0.html",
                "official_site": "http://www.goaland.com.cn", "last_verified": VERIFIED_DATE,
                "verify_note": "官网连接被拒未能核验（低置信）；招聘以 BOSS直聘企业账号为主，投递前请自行确认"},

    # ---------- 第三轮：链接体检回退（校招子域失效 → 官网首页，2026-08-30） ----------
        "aiko": {"apply_url": "https://www.aikosolar.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "baowu": {"apply_url": "https://www.baowugroup.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "calb": {"apply_url": "https://www.calb-tech.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "canadian-solar": {"apply_url": "https://www.canadiansolar.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "casc": {"apply_url": "https://www.spacechina.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "cetc": {"apply_url": "https://www.cetc.com.cn", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "changan": {"apply_url": "https://www.changan.com.cn", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "chery": {"apply_url": "https://www.chery.cn", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "cimc": {"apply_url": "https://www.cimc.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "cnooc": {"apply_url": "https://www.cnooc.com.cn", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "comac": {"apply_url": "https://www.comac.cc", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "cr-power": {"apply_url": "https://www.crpower.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "crrc": {"apply_url": "https://www.crrcgc.cc", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "cssc": {"apply_url": "https://www.cssc.net.cn", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "cxmt": {"apply_url": "https://www.cxmt.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "danfoss": {"apply_url": "https://www.danfoss.cn", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "delixi": {"apply_url": "https://www.delixi-electric.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "delta": {"apply_url": "https://www.delta-emea.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "east-group": {"apply_url": "https://www.eastgroup.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "estun": {"apply_url": "https://www.estun.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "eve": {"apply_url": "https://www.evebattery.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "fii": {"apply_url": "https://www.fii-foxconn.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "gac-aion": {"apply_url": "https://www.gacne.com.cn", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "galanz": {"apply_url": "https://www.galanz.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "geely": {"apply_url": "https://zgh.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "ginlong": {"apply_url": "https://www.ginlong.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "goertek": {"apply_url": "https://www.goertek.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "goldwind": {"apply_url": "https://www.goldwind.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "goodwe": {"apply_url": "https://www.goodwe.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "guanhao": {"apply_url": "https://www.guanhao.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "gwm": {"apply_url": "https://www.gwm.com.cn", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "haier": {"apply_url": "https://www.haier.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "hanslaser": {"apply_url": "https://www.hanslaser.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "harbin": {"apply_url": "https://www.harbin-electric.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "hikvision": {"apply_url": "https://www.hikvision.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "hisense": {"apply_url": "https://www.hisense.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "hitachi-energy": {"apply_url": "https://www.hitachienergy.com/cn", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "hithium": {"apply_url": "https://www.hithium.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "huahong": {"apply_url": "https://www.huahong.com.cn", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "hymson": {"apply_url": "https://www.hymson.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "invt": {"apply_url": "https://www.invt.com.cn", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "ja-solar": {"apply_url": "https://www.jasolar.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "jingneng": {"apply_url": "https://www.powerbeijing.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "jinko": {"apply_url": "https://www.jinkosolar.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "jinpan": {"apply_url": "https://www.jinpan.com.cn", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "jpt": {"apply_url": "https://www.jpt.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "kewa": {"apply_url": "https://www.kehua.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "kstar": {"apply_url": "https://www.kstar.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "leapmotor": {"apply_url": "https://www.leapmotor.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "leoch": {"apply_url": "https://www.leoch.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "longi": {"apply_url": "https://www.longi.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "luxshare": {"apply_url": "https://www.luxshare-ict.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "megmeet": {"apply_url": "https://www.megmeet.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "mindray": {"apply_url": "https://www.mindray.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "mingyang": {"apply_url": "https://www.myse.com.cn", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "nanzi": {"apply_url": "https://www.sac-china.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "nrec": {"apply_url": "https://www.nrec.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "oppo": {"apply_url": "https://www.oppo.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "saic-gmw": {"apply_url": "https://www.sgmw.com.cn", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "sany": {"apply_url": "https://www.sany.com.cn", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "sdic": {"apply_url": "https://www.sdicpower.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "shenergy": {"apply_url": "https://www.shenergy.com.cn", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "shenzhen-metro": {"apply_url": "https://www.szmc.net", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "sieyuan": {"apply_url": "https://www.sieyuan.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "sinexcel": {"apply_url": "https://www.sinexcel.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "smic": {"apply_url": "https://www.smics.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "svolt": {"apply_url": "https://www.svolt.cn", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "tgood": {"apply_url": "https://www.tec.cn", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "tongwei": {"apply_url": "https://www.tongwei.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "trinasolar": {"apply_url": "https://www.trinasolar.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "united-imaging": {"apply_url": "https://www.united-imaging.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "vertiv": {"apply_url": "https://www.vertiv.cn", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "wanhua": {"apply_url": "https://www.whchem.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "weichai": {"apply_url": "https://www.weichai.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "wuxi-lead": {"apply_url": "https://www.leadintel.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "xcmg": {"apply_url": "https://www.xcmg.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "xinje": {"apply_url": "https://www.xinje.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "xj": {"apply_url": "https://www.xjgc.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "ymtc": {"apply_url": "https://www.ymtc.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "zeekr": {"apply_url": "https://www.zeekrlife.com", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "zheneng": {"apply_url": "https://www.zjenergy.com.cn", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    "zte": {"apply_url": "https://www.zte.com.cn", "last_verified": None,
             "verify_note": "校招子域探测失效，已回退官网首页（请从官网导航到招聘频道投递）；入口待核验"},
    # ---------- 第四轮：链接体检手工修正（2026-08-30） ----------
    "baiyun": {"apply_url": "http://www.baiyundianqi.com", "official_site": "http://www.baiyundianqi.com",
               "last_verified": VERIFIED_DATE,
               "verify_note": "原域名失效；官网已更正为 baiyundianqi.com（公共 DNS 解析确认 + HTTP 200）"},
    "crrc-zelri": {"apply_url": "https://www.zelri.com.cn", "official_site": "https://www.zelri.com.cn",
               "last_verified": VERIFIED_DATE,
               "verify_note": "原 zelri.com 域名解析失败；已更正为 zelri.com.cn（公共 DNS 确认），站点响应慢属正常"},

    # ---------- 第五轮：链接体检批量修正（2026-08-30 深夜，8 家死链逐家搜索真域名） ----------
    "boje": {"apply_url": "https://www.zhbojay.com", "official_site": "https://www.zhbojay.com",
             "last_verified": VERIFIED_DATE,
             "verify_note": "官网已更正为 zhbojay.com（「测试及自动化专家」，HTTP 200 确认）；招聘栏目在官网导航内"},
    "guangqing": {"apply_url": "https://www.gqjs.com.cn", "official_site": "https://www.gqjs.com.cn",
             "last_verified": VERIFIED_DATE,
             "verify_note": "官网已更正为 gqjs.com.cn（广东广青金属科技，HTTP 200 确认）"},
    "guangzhou-metro": {"apply_url": "http://www.gzmtr.com", "official_site": "http://www.gzmtr.com",
             "last_verified": VERIFIED_DATE,
             "verify_note": "官网已更正为 gzmtr.com（无连字符；HTTP 200 确认），招聘走集团官网「人才招聘」栏目"},
    "hengli": {"apply_url": "https://www.hengli.com", "official_site": "https://www.hengli.com",
             "last_verified": VERIFIED_DATE,
             "verify_note": "官网已更正为恒力集团 hengli.com（HTTP 200 确认）；恒力石化（大连）招聘信息在集团官网发布"},
    "mingyang-elec": {"apply_url": "https://www.mingyang.com.cn", "official_site": "https://www.mingyang.com.cn",
             "last_verified": VERIFIED_DATE,
             "verify_note": "官网已更正为 mingyang.com.cn（301291，HTTP 200 确认）"},
    "sifang": {"apply_url": "https://www.sf-auto.com", "official_site": "https://www.sf-auto.com",
             "last_verified": VERIFIED_DATE,
             "verify_note": "官网已更正为 sf-auto.com（601126 四方股份，HTTP 200 确认）；校招岗位在官网人才栏目"},
    "united-winners": {"apply_url": "https://www.uwlaser.com", "official_site": "https://www.uwlaser.com",
             "last_verified": VERIFIED_DATE,
             "verify_note": "官网已更正为 uwlaser.com（688518 联赢激光，HTTP 200 确认）"},

    # ---------- 第六轮：机器人/具身智能链接核验（2026-08-30，含薪资档更新） ----------
    "ubtech": {"apply_url": "https://m.liepin.com/company/8095160/", "official_site": "https://www.ubtrobot.com/cn",
             "last_verified": VERIFIED_DATE, "verify_note": "官网+猎聘双通道已核验；猎聘在招机器人维修 17-25k、机械资深（行星减速器舵机）30-50k，量产爬坡期电气需求持续",
             "salary_text": "本科约 12-18k×(13-15)（社招硬件电气岗 17-50k）"},
    "dobot": {"apply_url": "https://dobot.zhiye.com/", "official_site": "https://www.dobot.cn",
             "last_verified": VERIFIED_DATE, "verify_note": "北森官方招聘平台已核验；BOSS直聘在招电气工程师（南山，机电/电气自动化专业）",
             "salary_text": "本科约 12-16k×(13-15)（硬件测试 15-20k·14薪）"},
    "limx": {"apply_url": "https://career.limxdynamics.com/", "official_site": "https://www.limxdynamics.com/zh",
             "last_verified": VERIFIED_DATE, "verify_note": "官网招聘系统已核验；硬件岗明确要求 PMSM/BLDC 电机驱动电路、高精度电流采样、EtherCAT/CAN FD 电气接口",
             "salary_text": "本科约 13-18k×(13-15)，初创期权"},
    "lejurobot": {"apply_url": "https://m.liepin.com/company/9094690/", "official_site": "https://www.lejurobot.com/zh",
             "last_verified": VERIFIED_DATE, "verify_note": "猎聘已核验：在招控制硬件工程师（功率电路方向）15-25k",
             "salary_text": "本科约 10-15k×13（控制硬件 15-25k）"},
    "engineai": {"apply_url": "https://dx3a2bminsq.jobs.feishu.cn/", "official_site": "https://www.engineai.com.cn/",
             "last_verified": VERIFIED_DATE, "verify_note": "飞书官方招聘已核验：电子硬件工程师 30-50k、电机驱动硬件工程师 25-50k·14薪",
             "salary_text": "本科约 12-16k×(13-15)（电机驱动硬件 25-50k·14薪）"},
    "astibot": {"apply_url": "https://www.astibot.com", "official_site": "https://www.astibot.com",
             "last_verified": VERIFIED_DATE, "verify_note": "官网已确认；投递以邮件 join@astribot.com 及猎聘为主；猎聘硬件测试 15-30k·14薪、电气工艺 15-35k·14薪",
             "salary_text": "本科约 12-16k×(13-15)（硬件测试/电气工艺 15-35k·14薪）"},
    "youibot": {"apply_url": "https://youibot1.zhiye.com/campus/jobs", "official_site": "https://zh.youibot.com/",
             "last_verified": VERIFIED_DATE, "verify_note": "北森校招页已核验：2026届校招研发岗面向电气自动化专业",
             "salary_text": "本科约 10-14k×(13-14)"},
    "agilex": {"apply_url": "https://mammotion.jobs.feishu.cn/AgileX_campus_recruitment", "official_site": "https://www.agilex.ai/",
             "last_verified": VERIFIED_DATE, "verify_note": "飞书官方校招已核验：2026校招含硬件工程师，覆盖深圳/东莞/成都三地",
             "salary_text": "本科约 10-14k×13", "cities": ["深圳", "东莞", "成都"]},
    "xag": {"apply_url": "https://www.xa.com/about/career", "official_site": "https://www.xa.com/",
             "last_verified": VERIFIED_DATE, "verify_note": "官网招聘页已核验；BOSS直聘：BMS 系统硬件方案、电机驱动系统电路设计岗",
             "salary_text": "本科约 11-15k×(13-15)（硬件岗 14-28K）"},
    "crprobot": {"apply_url": "https://www.crprobot.com/c/zhaopin.html", "official_site": "https://www.crprobot.com/",
             "last_verified": VERIFIED_DATE, "verify_note": "官网招聘页已核验；猎聘伺服硬件工程师 25-35K（IGBT 功率电路、电机主驱动）+ 初级硬件 12-20K（人形机器人电控）",
             "salary_text": "本科约 8-12k×13（伺服硬件 25-35K）"},
}